docs/contents.rst.inc, docs/intro/installation.rst
Start a section on how to install DataLad.
So far the content is copy-pasted from the [docs](docs.datalad.org) and the [website](datalad.org).
Some TODOs concern
- adding some information (I'm not sure what the current status is, but at least a "it does not work, you can use a virtual machine, ...") for Windows users and 
- a less intimidating way of talking about non-admin installation of git-annex
=> Installation instructions in the Introduction section

docs/glossary.rst, docs/intro/datasets.rst, docs/intro/philosophy.rst
This is work in progress for a section on the core principles of DataLad. So far it incorporates the points made by mih in his youtube talk.
=> Philosophy / Principles of Datalad

artwork/social-card.svg
Contains the .svg of our current [social card](https://github.com/datalad-handbook/book/settings).
=> add social card to address #34

.travis.yml
Can be merged if it doesn't break the test runs.
=> Try to speed up Travis runs

docs/intro/narrative.rst
Don't tell your readers to leave before finishing the introduction :]
=> narrative: Fix typo

docs/conf.py
This prevents scrolling back to the top to switch chapters.
Addresses #61.
=> ENH: have sidebar fixed

docs/conf.py, docs/intro/howto.rst
Started to use figure captions, too
=> Small tune-ups to improve the visual impression

docs/basics/101-101-create.rst
Will merge this as a test, once the tests pass.
=> Readthedocs build crashes (due to missing section number?)

setup.py
Same game, will merge when tests passed.
=> Try forcing dep. on Sphinx>2 to get readthedocs to work

docs/basics/101-102-populate.rst, docs/basics/101-105-install.rst, docs/basics/101-108-run.rst, docs/basics/101-110-run2.rst, docs/basics/101-111-run3.rst, docs/basics/101-115-symlinks.rst, docs/basics/101-121-siblings.rst, docs/basics/101-125-config.rst, docs/intro/narrative.rst
Changes the "header" section of existing toggled containers from "additional content" to "Find out more".
=> Additional Content --> Find out more

docs/basics/101-102-populate.rst, docs/basics/101-105-install.rst, docs/basics/101-108-run.rst, docs/basics/101-110-run2.rst, docs/basics/101-111-run3.rst, docs/basics/101-115-symlinks.rst, docs/basics/101-121-siblings.rst, docs/intro/narrative.rst
Thanks to #120 , we can now use the custom ``findoutmore`` directive everywhere.
=> transform containers into findoutmore directive

README.md
reducing the TODOs in the readme, adding some color
=> Improve first look

docs/contributing.rst
We should add information to the contributing file to enable contributions, for example about the necessary software to build the book locally.
Here is just a rough draft, I will readdress this before Thursday.
=> Improve Contributing

docs/conf.py, docs/contents.rst.inc
=> Minor tuneups, and fix #148

.all-contributorsrc
Q is now, if the bot can handle to when the next update happens.
=> Hand-polish contributor name

.zenodo.json, CONTRIBUTORS.md, README.md, docs/contributing.rst
This includes information and contributors, and how to add contributors to our acknowledgments.
=> WIP: Contribution acknowledgements, fixes #140

docs/basics/101-115-symlinks.rst, docs/basics/101-123-yoda.rst, docs/basics/101-125-config.rst, docs/basics/101-140-filesystem.rst, docs/contributing.rst, docs/glossary.rst, docs/intro/howto.rst, docs/intro/installation.rst, docs/intro/philosophy.rst, docs/usecases/supervision.rst
This mostly fixes not-working or missing links/refs, and adds some missing glossary and index entries.
=> Links, glossary, index fixes

.github/ISSUE_TEMPLATE/bug_report.md, docs/basics/101-101-create.rst, docs/basics/101-102-populate.rst, docs/basics/101-103-modify.rst, docs/basics/101-105-install.rst, docs/basics/101-115-symlinks.rst, docs/basics/101-116-sharelocal.rst, docs/basics/101-125-config.rst, docs/basics/101-126-config2.rst, docs/basics/101-135-help.rst, docs/basics/101-140-filesystem.rst, docs/basics/_examples/DL-101-105-111, docs/basics/_examples/DL-101-106-101, docs/basics/_examples/DL-101-108-106, docs/basics/_examples/DL-101-119-101, docs/basics/_examples/DL-101-119-103, docs/contributing.rst, docs/intro/installation.rst
Please see individual commits for more explanation.
=> Minor typo fixes, rewordings, and an addition

docs/basics/101-105-install.rst, docs/basics/101-123-yoda.rst, docs/basics/101-126-config2.rst, docs/basics/101-140-filesystem.rst, docs/basics/_examples/DL-101-135-103, docs/contributing.rst, docs/glossary.rst, docs/usecases/supervision.rst
This changes instances of ``i.e.`` (British English) to ``i.e.,`` (American English) for consistency.
=> Change i.e. to i.e., 

docs/basics/101-126-config2.rst, docs/basics/101-127-procedures.rst, docs/basics/_examples/DL-101-125-114, docs/basics/_examples/DL-101-127-112
Forgot to add a datalad save after modifications of ``notes.txt``.
=> Fix: add missing dl-save

docs/contents.rst.inc, docs/usecases/inm7_analysis_project.rst, docs/usecases/inm7_hammerpants.rst, docs/usecases/inm7_jsc_data.rst
A first PR against the ``inm7`` branch. It adds a new chapter ``Use Cases: INM-7 FZJ`` and placeholders for three potentially relevant use cases with some brief TODOs.
I have protected the ``inm7`` branch against pushing without PRs just as in the master branch.
=> a toy PR for inm7, some outline for relevant usecases

Makefile, README.md, docs/basics/101-101-create.rst, docs/basics/101-102-populate.rst, docs/basics/101-103-modify.rst, docs/basics/101-105-install.rst, docs/basics/101-106-nesting.rst, docs/conf.py, docs/contributing.rst, requirements.txt
Includes currently relevant changes to `conf.py` and some tags. I assume builds will fail due to un-updated autorunrecord atm.
=> Proof-of-concept tests for autorunrecord2casts

docs/basics/101-108-run.rst, docs/basics/101-109-rerun.rst, docs/basics/101-110-run2.rst, docs/basics/101-112-run4.rst, docs/basics/_examples/DL-101-108-113, docs/basics/_examples/DL-101-108-115, docs/basics/_examples/DL-101-112-109
Minor caption and code changes to ensure smooth casts for session on "DataLad, Run!"
=> modifications for session 02

docs/intro/philosophy.rst
seems that the alternative was : if you dont know git, ... otherwise, if you dont know git ... :)
=> if you do know git ... and if you dont

docs/404.rst, docs/basics/101-102-populate.rst, docs/basics/101-103-modify.rst, docs/basics/101-105-install.rst, docs/basics/101-107-summary.rst, docs/basics/101-109-rerun.rst, docs/basics/101-110-run2.rst, docs/basics/101-114-txt2git.rst, docs/basics/101-115-symlinks.rst, docs/basics/101-116-sharelocal.rst, docs/basics/101-117-sharelocal2.rst, docs/basics/101-121-siblings.rst, docs/basics/101-123-yoda.rst, docs/basics/101-125-config.rst, docs/basics/101-126-config2.rst, docs/basics/101-127-procedures.rst, docs/basics/101-135-help.rst, docs/basics/101-136-history.rst, docs/basics/101-140-filesystem.rst, docs/contents.rst.inc, docs/contributing.rst, docs/intro/howto.rst, docs/intro/installation.rst, docs/intro/narrative.rst, docs/intro/philosophy.rst, docs/usecases/collaborative_data_management.rst, docs/usecases/datasets.rst, docs/usecases/provenance_tracking.rst, docs/usecases/reproducible-paper.rst, docs/usecases/supervision.rst
=> Remove contractions for improved accessibility

docs/code_from_chapters/01_dataset_basics_code.rst, docs/code_from_chapters/02_reproducible_execution_code.rst, docs/contents.rst.inc
=> rename casts to chapters

docs/_static/custom.css
This will justify all text in the handbooks html version. Its a matter of personal taste, what do the others think about this?
=> justify text alignment

docs/intro/howto.rst
Hi there,
As mentioned in an issue, here is the pull request to correct the name of Adina's machine in the code snippet :-)
=> Typo in name of machine

docs/basics/101-101-create.rst, docs/basics/101-102-populate.rst, docs/basics/101-103-modify.rst, docs/basics/101-105-install.rst, docs/basics/101-108-run.rst, docs/basics/101-109-rerun.rst, docs/basics/101-112-run4.rst, docs/basics/101-118-sharelocal3.rst, docs/basics/101-122-config.rst, docs/basics/101-123-config2.rst, docs/basics/101-130-yodaproject.rst
(have only done the first half of the book, the other will come soon)
=> some updating after linting for insensitive words

docs/basics/101-115-symlinks.rst, docs/basics/101-116-sharelocal.rst, docs/glossary.rst, docs/usecases/collaborative_data_management.rst
add overview of different file system permissions to glossary, and fix a few typos on the way
=> add permissions to glossary

docs/basics/101-105-install.rst, docs/basics/101-180-FAQ.rst
I'm taking a few things not yet mentioned in the handbook from [this file](https://github.com/datalad/datalad/pull/3355/files) and add them as a Gitusernote and or an addition to a question in the FAQ
=> Recycle bits from https://github.com/datalad/datalad/pull/3355/

docs/basics/101-105-install.rst, docs/basics/101-115-symlinks.rst, docs/basics/101-130-yodaproject.rst, docs/basics/101-180-FAQ.rst, docs/img/virtual_dirtree.svg, docs/intro/philosophy.rst, docs/usecases/datastorage_for_institutions.rst, docs/usecases/reproducible_neuroimaging_analysis.rst, docs/usecases/supervision.rst
Few fixes re treating 'data' as a singular word.
=> 'data are'

docs/basics/101-132-advancednesting.rst, docs/basics/_examples/DL-101-132-101, docs/basics/_examples/DL-101-132-103, docs/basics/_examples/DL-101-132-105, docs/basics/_examples/DL-101-132-106, docs/basics/_examples/DL-101-132-107, docs/basics/_examples/DL-101-132-108, docs/basics/_examples/DL-101-132-109, docs/basics/_examples/DL-101-132-110, docs/basics/_examples/DL-101-132-112
This adds a findoutmore to the advanced nesting section to highlight some of the more advanced functionality of ``datalad status``.
=> add hidden section that elaborates on datalad status

docs/basics/101-130-yodaproject.rst, docs/usecases/datastorage_for_institutions.rst
Just a couple quick typo fixes.
=> fix a few typos

docs/contents.rst.inc
I'm adding a "Basics <nr>" prefix to every chapter of the Basics. I hope that this helps to distinguish Introduction, Basics, and Usecases.
=> attempt to distinguish basics from other parts in html toctree

.zenodo.json
This makes the repository ready for the next release. Fixes #220 for now.
=> Finalize zenodo

docs/basics/101-102-populate.rst
previous URL did not point to PDF anymore. Fixes #331.
=> provide new book link

docs/basics/_examples/DL-101-102-103
I forgot to add the example file when fixing the book link in #332, will merge this once tests pass.
=> add forgotten example file

docs/code_from_chapters/02_reproducible_execution_code.rst
Minor updates to the code lists after recent additions to the book. For this casts, only numbering was off. #333 has an update of the first code list that is more substantial.
=> update code list from second chapter

CHANGELOG.md
=> add final changes about tagged showroom repos

docs/basics/101-127-yoda.rst, docs/basics/101-138-sharethirdparty.rst
This fixes #344, at least partially.
=> remove hardcoded instances of adswa or adina

.zenodo.json
Added info to .zenodo.json ([ref](https://github.com/datalad-handbook/book/pull/348#issuecomment-574077802))
=> added info to zenodo

docs/basics/101-179-gitignore.rst
This fixes  #343. I have added two hidden sections, one on general rules for .gitignore files, and one on how to create global rules for ignoring contents.
=> More about .gitignore

docs/intro/installation.rst
=> Enhance installation page with 7 zip for windows and upgrading info

docs/basics/101-136-filesystem.rst, docs/basics/_examples/DL-101-136-125, docs/basics/_examples/DL-101-136-127, docs/basics/_examples/DL-101-136-128, docs/basics/_examples/DL-101-136-129, docs/basics/_examples/DL-101-136-180, docs/basics/_examples/DL-101-136-181, docs/basics/_examples/DL-101-136-182, docs/basics/_examples/DL-101-136-183, docs/basics/_examples/DL-101-136-184, docs/basics/_examples/DL-101-136-185, docs/basics/_examples/DL-101-136-186, docs/basics/_examples/DL-101-136-187, docs/basics/_examples/DL-101-136-188, docs/basics/_examples/DL-101-136-189
This addition was inspired by @sarah1989. @all-contributors please add @sarah1989 for ideas
=> On moving contents across dataset boundaries, fixes #387

requirements.txt
This tries to fix #398 (not sure whether this works)
=> BF: attempt to specify handbook support in requirements.txt

docs/basics/101-138-sharethirdparty.rst
Please see individual commits messages for rationale etc.
=> ENH: various tune ups and extension to the section on special remotes

docs/basics/101-138-sharethirdparty.rst
can't push directly, thus a PR ;)
=> minor: removed duplicate "enable"

README.md, docs/_templates/sidebarintro.html, docs/basics/101-101-create.rst, docs/basics/101-105-install.rst, docs/basics/101-108-run.rst, docs/basics/101-109-rerun.rst, docs/basics/101-124-procedures.rst, docs/basics/101-137-history.rst, docs/basics/_examples/DL-101-124-112, docs/basics/_examples/DL-101-137-101, docs/basics/_examples/DL-101-137-121, docs/glossary.rst, docs/usecases/datasets.rst, docs/usecases/reproducible-paper.rst
Not sure if second commit is "safe" (no side-effects due to ')
=> ENH: consistent DataLad and DataLad's

docs/basics/101-133-containersrun.rst
as I was asking this myself earlier today, I thought it would be good to have an example in the handbook.
=> example commands for local containers and Docker images

docs/basics/101-124-procedures.rst, docs/basics/101-136-cheatsheet.rst, docs/intro/executive_summary.rst
Reverts datalad-handbook/book#427
=> Revert "TMP/BF: Preview cheatsheet"

docs/contributing.rst
This adds the Beyond Basics part to the explanation of the book structure.
=> Contributing: Update to reflect the 4-part structure of the book

docs/basics/101-116-sharelocal.rst, docs/basics/101-138-sharethirdparty.rst
=> Minor tweaks to sections concerned with dataset sharing

docs/beyond_basics/101-144-intro_extensions.rst
Following https://github.com/datalad/datalad/issues/4490, this should mention all available extensions and either link to existing sections about the respective extension, or have a TODO to an associated work-in-progress PR
=> Extensions: Complete list of extensions for datalad

.all-contributorsrc, .zenodo.json
- to zenodo.json
- to allcontributorsrc
TODO: use bot to add giulia
Fixes #471
=> Zenodo: add new contributor names

docs/basics/101-138-sharethirdparty.rst
Basically copy-pasted from https://github.com/datalad/datalad/issues/4489.
=> Minor additions to Git LFS section on compression/encryption and drop

docs/basics/101-146-gists.rst, docs/glossary.rst
=> New Gist: Squash annex history

.zenodo.json
This puts him into the official, citeable author list of the book.
=> zenodo: Add Christian

docs/basics/101-101-create.rst, docs/basics/101-102-populate.rst, docs/basics/101-105-install.rst, docs/basics/101-116-sharelocal.rst, docs/basics/101-122-config.rst, docs/intro/installation.rst, docs/intro/philosophy.rst, docs/intro/user_types.rst
A few spelling/grammar errors corrected.
There are also a few suggestions to remove, shift, or replace text. Feel free to drop those :-)
=> BF: fix spelling and propose small changes

docs/beyond_basics/101-146-providers.rst, docs/beyond_basics/101-147-riastores.rst, docs/beyond_basics/101-160-gobig.rst, docs/beyond_basics/101-161-biganalyses.rst, docs/beyond_basics/101-162-springcleaning.rst, docs/intro/installation.rst
I'm checking whether RTD PR builds happen now.
=> typos to check RTD builds

docs/index.rst, docs/r.rst
I'm trying to get redirection to work. Don't mind these PR's, even if they don't work, they only introduce hidden documents.
=> WIP: try out redirection

docs/extension_pkgs.rst, docs/r.rst
Sits on top of https://github.com/datalad-handbook/book/pull/525 (to avoid conflicts) but is pretty much orthogonal.
=> Misc extension-related updates

docs/extension_pkgs.rst
fixes adswa/git-annex-remote-osf#12
=> Add DataLad OSF to extensions_pkg.rst

CHANGELOG.md
Generated with the help of
```
git log --format="?  %s%n   %h^-1" --reverse --first-parent ee85ca254b0cfa7605070ff4d9e7ec8303e4a8db..0246c38211228c448d698fb056a5b82a13ecf2c0
```
=> Start a Changelog for 0.13

.zenodo.json
PR to add @ayrustogaru to .zenodo.json .
=> zenodo: Add ayrustogaru

README.md
I messed this up and accidentally deleted the badge ;-)
=> Revert "BF: fix allcontributors counting"

dataladhandbook_support/directives.py, docs/_static/custom.css, docs/basics/101-101-create.rst, docs/basics/101-106-nesting.rst, docs/basics/101-124-procedures.rst, docs/conf.py, docs/glossary.rst, docs/intro/narrative.rst
- adds a custom "Windows Workaround" Container (i.e., a findoutmore in blue with a different title)
- Provides windows users with a custom dataset configuration to replace `text2git`.
=> Windows-Adjustments

docs/basics/101-180-FAQ.rst, docs/beyond_basics/101-164-dataladdening.rst, docs/beyond_basics/basics-retrospective.rst, docs/beyond_basics/intro.rst
Fixes #539 when its done.
This starts a chapter or section on transforming an existing project into a datalad dataset. This isn't anywhere yet, but I'm opening the PR so that others can chime in with ideas if they wish.
=> Transition existing projects to DataLad

docs/basics/101-127-yoda.rst
If you still prefer to use a contraction here, please use "It's".
=> FIX: Replace contraction of "It is" to "Its".

docs/intro/installation.rst
should fix #556
I love the smell of a PR in the morning. :fire: :fire: :fire:
=> Fix dead link to doc

.zenodo.json, README.md, docs/contributing.rst
Adding myself and contribution info.
Let me know if you want to update the DOI badge to point to the "All version DOI".
=> update contributors info

.zenodo.json
Added my information to the file as explained by @adswa 
(hopefully correct :))
=> add contributor information to .zenodo.json

docs/usecases/supervision.rst
adds a yet missing cheatsheet link. Thx for @mih for finding it
=> supervision: link cheatsheet

.github/config.yml
I saw the welcome app being used by the OHBM hackathon team - its a bot that greets and congratulates first time contributors on their issues, PRs, and PR merges. I enabled the app a while ago already, but this now adds a config file that defines the messages. The wonderful images come from the Turing Way Project. :)
=> Have a welcome bot

docs/basics/101-138-sharethirdparty.rst
Given how easy it is to use the OSF with the new extension, I have placed a note about the OSF into the "here are easier alternatives" box.
=> Mention osf extension in third party chapter

docs/beyond_basics/101-168-dvc.rst, docs/beyond_basics/_examples/DL-101-168-141
This one slipped through, I didn't update the code example after switching from publish (used due to my "push.default = matching" configuration) back to push when we identified the problem.
=> DVC: Fix-up publish-push confusion in code block

docs/basics/101-138-sharethirdparty.rst
+  fix a few linebreaks
This closes #535.
=> Third party: mention prefix option of initremote.

docs/basics/101-101-create.rst, docs/basics/101-123-config2.rst, docs/intro/installation.rst, docs/intro/windows.rst
No instructions or advise, but notes on the fact that it exists and where to find it.
=> Windows: Mention git-annex with MagicMime

docs/r.rst
=> add a redirection for the MPIB workshop

docs/r.rst
for https://github.com/datalad/datalad/pull/5311
=> add a redirection to subds clone priorities for datalad #5311

docs/conf.py, docs/intro/philosophy.rst
A picture says more than 1000 words:
=> Minor changes re code-blocks in PDF

docs/basics/101-135-help.rst, docs/beyond_basics/101-145-hooks.rst, docs/book_appendix.rst, docs/conf.py, docs/extension_pkgs.rst
- de-uglify all tables
- bold table headers
- all tables referenced in-text
- table/figure number per-chapter (like everything else)
- list all boxes, figures, tables in appendix
=> Bettertables

docs/intro/installation.rst
- base installation on brew
- move pip installation more into paragraph on pip
=> Install: Rework macOS installation

dataladhandbook_support/directives.py, dataladhandbook_support/roles.py, docs/_static/custom.css, docs/basics/101-101-create.rst, docs/basics/101-102-populate.rst, docs/basics/101-103-modify.rst, docs/basics/101-105-install.rst, docs/basics/101-108-run.rst, docs/basics/101-109-rerun.rst, docs/basics/101-110-run2.rst, docs/basics/101-115-symlinks.rst, docs/basics/101-121-siblings.rst, docs/basics/101-123-config2.rst, docs/basics/101-124-procedures.rst, docs/basics/101-130-yodaproject.rst, docs/book_appendix.rst, docs/code_from_chapters/ABCD.rst, docs/code_from_chapters/DLBasicsMPI.rst, docs/code_from_chapters/usecase_ml_code.rst, docs/conf.py, docs/intro/installation.rst, docs/intro/narrative.rst, docs/usecases/ml-analysis.rst
In the same spirit as the recent find-out-more upgrade, but additionally
also renaming with a more positive attitude.
Plus some demo references.
=> windowsworkarounds -> windows-wit

docs/code_from_chapters/yale.rst, docs/index.rst, docs/r.rst
Ping @yarikoptic: Here's a rough sketch for a datalad intro. Please take a look and add what else you would want to include.
=> Add a rough sketch of a DataLad intro for Repronim workshop in Yale

.github/workflows/github-action.yml
=> Adds a Github-actions based CI setup

docs/r.rst
=> add redirects for chapters mentioned in ukb manuscript

docs/basics/101-122-config.rst, docs/basics/101-130-yodaproject.rst, docs/beyond_basics/101-171-enki.rst, docs/intro/howto.rst, docs/intro/narrative.rst, docs/intro/windows.rst
=> Another sweep for printing

docs/basics/101-130-yodaproject.rst, docs/basics/101-135-help.rst, docs/basics/101-180-FAQ.rst
=> Add FAQ on GitHub displaying git-annex as the default

docs/basics/101-108-run.rst, docs/intro/windows.rst
This adds a windows wit to help alleviate the confusion that was the cause for #715.
Fixes #716, fixes #715
=> Windows weird behavior with file extensions

docs/basics/101-110-run2.rst, docs/basics/101-127-yoda.rst, docs/beyond_basics/101-170-dataladrun.rst
=> Mention --dry-run

docs/code_from_chapters/yale.rst
With thanks for the bug report to @cni-md
=> Fix left-over exit code

.github/workflows/linkcheck.yml
Let's see if that helps to fix #741
=> Add a monthly cron job to check links in the handbook

docs/basics/101-102-populate.rst
I believe this is the correct word here.
=> "ultimatively" => "ultimately"

docs/basics/101-105-install.rst
=> Fixes typo

Makefile, docs/_static/custom.css, docs/contributing.rst
=> [FIX] update css unordered list in important note when viewing

Makefile
=> BF: Makefile - replace leading spaces with tabs

.github/workflows/github-action.yml, docs/basics/101-121-siblings.rst, docs/beyond_basics/101-160-gobig.rst, docs/conf.py
=> Link fixes for failing link check

docs/code_from_chapters/ABCD.rst, docs/code_from_chapters/DLBasicsMPI.rst, docs/code_from_chapters/dgpa.rst, docs/code_from_chapters/yale.rst, docs/index.rst, docs/r.rst, requirements.txt
For a two-hour code-along workshop for the ReproNim/DGPA workshop. Includes minor fixes in the code-cast sections for rendering the toctrees correctly.
=> DGPA workshop contents

docs/basics/101-127-yoda.rst
The figure "names" was wrong. I changed it to the correct one.
=> fix wrong figure name

docs/conf.py, requirements-devel.txt, requirements.txt
in an attempt to fix #822, #821
=> Remove version pinning of Sphinx

.zenodo.json
=> Add Ikko Ashimine to zenodo.json

CHANGELOG.md, docs/basics/101-139-gin.rst, docs/extension_pkgs.rst, docs/intro/windows.rst
This PR adds the final bits to conclude the ``0.15`` version of the handbook.
=> Release fixes

docs/basics/101-115-symlinks.rst
=> Fix typo there -> their

docs/basics/101-139-gitlfs.rst
=> ENH: mention publication dependency in git-lfs section

docs/beyond_basics/101-147-riastores.rst, docs/beyond_basics/_examples/DL-101-147-101, docs/beyond_basics/_examples/DL-101-147-103, docs/beyond_basics/_examples/DL-101-147-104, docs/beyond_basics/_examples/DL-101-147-105, docs/beyond_basics/_examples/DL-101-147-106, docs/beyond_basics/_examples/DL-101-147-108, docs/beyond_basics/_examples/DL-101-147-111, docs/beyond_basics/_examples/DL-101-147-112, docs/beyond_basics/_examples/DL-101-147-120, docs/beyond_basics/_examples/DL-101-147-121, docs/beyond_basics/_examples/DL-101-147-122, docs/beyond_basics/_examples/DL-101-147-123, docs/beyond_basics/_examples/DL-101-147-127
=> Mention alias parameter of create-sibling-ria

docs/intro/installation.rst
thanks @ajveltri22! Fixes #858
=> Remove M1 specific workarounds as it became available via brew

.zenodo.json
PR to add myself to .zenodo.json. Thanks!
=> Add Anthony Veltri to .zenodo.json

docs/code_from_chapters/OHBM.rst
I cannot believe I am making a contribution to DataLad even it is this tiny miny and maybe not useful anymore 🙄 But I benefit a lot from this tutorial for my work and I will call it _the best and most worthwhile procrastination ever!_ one can get once a life time! 🚀 
Thank you for this amazing tutorial and such an amazing tool you all 🤗
=> Fix some typos - best procrastination ever!

docs/basics/101-105-install.rst, docs/basics/101-106-nesting.rst, docs/basics/101-107-summary.rst, docs/intro/philosophy.rst
This PR contains many of the changes proposed by @candleindark in various open PRs, and one fixed link that the monthly linkcheck brought up.
I haven't used all of the changes proposed by @candleindark as there is quite a subjective element to this, but many of their commits were very useful suggestions and are included in this PR.
When this PR is merged, I will close the other PRs. Commit authorship has been kept, of course.
=> A number of rewordings and fixes

tools/rtd_analytics
=> Crude but functional helper to scrape handbook access analytics

CHANGELOG.md
Let's try to create a retrospective release :crossed_fingers:
=> Add a changelog for 0.17

Makefile
C&P mistake in the makefile, that would wipe out the wrong working directories.
=> BF: remove the right workdirs

tools/rtd_analytics
One can/must now pass a project name as a positional argument
=> Make analytics stats work with any RTD project

docs/beyond_basics/101-147-riastores.rst, docs/beyond_basics/101-168-dvc.rst, docs/beyond_basics/101-180-next.rst, docs/beyond_basics/101-181-metalad.rst, docs/intro/philosophy.rst
To address https://github.com/orgs/psychoinformatics-de/projects/26/views/1?pane=issue&itemId=25927072
=> Fix stale links identified by monthly linkchecker

docs/basics/101-180-FAQ.rst
=> Mention Gooey in FAQ on GUI

docs/basics/101-136-filesystem.rst, docs/basics/101-180-FAQ.rst
=> Mention git annex uninit in FAQ and file system operations

docs/basics/101-113-summary.rst
=> Cross-ref KBI content on interactive computing with datalad run

docs/basics/101-139-gitlfs.rst
=> Add autoenable=true to Gitlfs special remote

docs/basics/101-106-nesting.rst, docs/basics/101-110-run2.rst
Two minor errors I found while reading
=> two small errors fixed

.zenodo.json
As requested in https://github.com/datalad-handbook/book/pull/974#issuecomment-1647282033
=> Add myself to .zenodo.json

.github/config.yml, README.md, artwork/OHBM_2020.svg, docs/OHBMposter.rst, docs/_templates/sidebarintro.html, docs/_templates/sidebarlogo.html, docs/basics/101-136-cheatsheet.rst, docs/conf.py
=> Update various outdated URLs and settings

docs/basics/101-109-rerun.rst, docs/basics/101-122-config.rst, docs/basics/101-135-help.rst, docs/basics/101-137-history.rst, docs/basics/101-180-FAQ.rst, docs/intro/philosophy.rst
All from pushing the print version, but these make sense to have in general.
=> Fixes for various small issues

docs/basics/101-102-populate.rst, docs/basics/101-115-symlinks.rst, docs/basics/101-124-procedures.rst, docs/basics/101-130-yodaproject.rst, docs/basics/101-136-filesystem.rst, docs/basics/_examples/DL-101-115-103, docs/basics/_examples/DL-101-115-104, docs/basics/_examples/DL-101-130-107, docs/basics/_examples/DL-101-130-110, docs/basics/_examples/DL-101-135-101, docs/basics/_examples/DL-101-135-102, docs/basics/_examples/DL-101-135-103, docs/basics/_examples/DL-101-135-105, docs/basics/_examples/DL-101-136-101
=> Some small fixes, backported from the PDF effort

docs/basics/101-101-create.rst, docs/basics/101-110-run2.rst, docs/beyond_basics/101-146-providers.rst, docs/code_from_chapters/dgpa.rst, docs/intro/installation.rst, docs/intro/philosophy.rst, docs/intro/windows.rst
Fixes a range of issues in the print repo
=> Minor print issues

docs/intro/installation.rst
I also used the chance to (re)verify on a "dirty" windows system.
Closes #1031
=> Update (windows) installation instructions

docs/basics/101-180-FAQ.rst
to fix https://github.com/psychoinformatics-de/book-datalad-intro/issues/57
=> replace dark figure with light alternative

docs/intro/narrative.rst
=> Explain the ✂ symbol

docs/basics/101-133-containersrun.rst
As a fix for #1033. It would be nice to get @mih's opinion.
=> Add a FOM on docker installation on Windows

docs/basics/101-139-hostingservices.rst, docs/basics/101-146-gists.rst
=> consistent figure widths and captions in hostingservice chapter

docs/acknowledgements.rst, docs/intro/installation.rst
This changeset has two small changes that primarily avoid needlessly complex markup constructs.
=> Syntax clean

README.md, artwork/OHBM_2020.svg
This Changes the last few occurences.
Closes #959
=> Transition handbook links to `https`

docs/basics/101-123-config2.rst, docs/basics/101-124-procedures.rst, docs/basics/101-125-summary.rst, docs/basics/101-130-yodaproject.rst, docs/basics/101-139-hostingservices.rst
The linebreak was: .
gitmodules
=> add some words to prevent an awkward line break

docs/basics/101-130-yodaproject.rst, docs/beyond_basics/101-162-springcleaning.rst, docs/beyond_basics/101-179-gitignore.rst, docs/intro/howto.rst, docs/intro/installation.rst, docs/intro/narrative.rst
- a few random typo or punctuation changes
- consistent spelling of macOS as macOS
=> Some typo fixes and punctuation tweaks

docs/basics/101-101-create.rst, docs/basics/101-102-populate.rst, docs/basics/101-103-modify.rst, docs/basics/101-105-install.rst, docs/basics/101-108-run.rst, docs/basics/101-109-rerun.rst, docs/basics/101-110-run2.rst, docs/basics/101-115-symlinks.rst, docs/basics/101-121-siblings.rst, docs/basics/101-130-yodaproject.rst, docs/intro/installation.rst, docs/usecases/ml-analysis.rst
This aims to make them more accessible. The only way right now would be the list of boxes in the PDF rendering.
This is merely a first draft for relevant index entries. We need to add more to see the picture better.
=> Add windows-wits to index

docs/basics/101-110-run2.rst
Luckily, not many adjustments were needed. Fixes #1053
=> Fix up highlighting after log filtering

docs/intro/philosophy.rst
fixes #1068
I hope this improves things. I realize how I don't really have an intuition for singular or plural data, I hope I didn't miss spots. Thanks for pointing it out, @mslw
=> make data consistently plural

docs/basics/101-110-run2.rst, docs/intro/installation.rst
fixes https://github.com/datalad-handbook/book/issues/1083
=> standardize capitalization of installation index term

docs/basics/101-105-install.rst
It is impossible to put on a paper page otherwise.
=> Remove two looong names

requirements.txt
=> remove version pinning for copy-button

docs/basics/101-130-yodaproject.rst, docs/basics/101-138-sharethirdparty.rst, docs/basics/101-139-gin.rst, docs/code_from_chapters/neurohackademy.rst, docs/usecases/reproducible-paper.rst
=> replace image with figure directives

docs/latex/preamble_end.sty
=> Discontinue use of `enumitem`

docs/intro/windows.rst
=> remove outdated info on docker under windows

docs/basics/101-103-modify.rst, docs/basics/101-105-install.rst, docs/topic_index.rst
Follow-up to https://github.com/datalad-handbook/book/pull/1096
=> `here-document` -> `heredoc`

docs/basics/101-115-symlinks.rst, docs/basics/101-122-config.rst, docs/basics/101-132-advancednesting.rst, docs/basics/101-133-containersrun.rst, docs/basics/101-136-filesystem.rst, docs/basics/101-141-push.rst, docs/basics/basics-help.rst, docs/beyond_basics/101-164-dataladdening.rst, docs/beyond_basics/101-170-dataladrun.rst, docs/beyond_basics/101-171-enki.rst, docs/beyond_basics/101-183-gooey.rst, docs/code_from_chapters/DLBasicsMPI.rst, docs/code_from_chapters/usecase_ml_code.rst, docs/glossary.rst, docs/intro/filenaming.rst, docs/intro/installation.rst, docs/intro/user_types.rst, docs/usecases/datasets.rst, docs/usecases/datastorage_for_institutions.rst, docs/usecases/encrypted_annex.rst, docs/usecases/openneuro.rst, docs/usecases/provenance_tracking.rst, docs/usecases/reproducible-paper.rst, docs/usecases/using_globus_as_datastore.rst
=> Standardize `filesystem` -> `file system`

docs/basics/101-133-containersrun.rst, docs/basics/101-139-gin.rst
=> Uniform upper case `URL`

docs/basics/101-133-containersrun.rst, docs/basics/topic/container-imgcfg.rst
Aiming to minimize a big diff with the print branch
=> More FOM into topic file

docs/intro/narrative.rst
Fixes #1114 
I grepped for "chapter 1-12" and couldn't find other hard coded chapter references
=> Remove hardcoded chapter reference

docs/basics/basics-annex.rst, docs/basics/basics-collaboration.rst, docs/basics/basics-configuration.rst, docs/basics/basics-containers.rst, docs/basics/basics-datasets.rst, docs/basics/basics-help.rst, docs/basics/basics-run.rst, docs/basics/basics-thirdparty.rst, docs/basics/basics-yoda.rst, docs/basics/intro.rst, docs/beyond_basics/basics-advancedoptions.rst, docs/beyond_basics/basics-dataladinternals.rst, docs/beyond_basics/basics-extensions.rst, docs/beyond_basics/basics-hpc.rst, docs/beyond_basics/basics-retrospective.rst, docs/beyond_basics/basics-scaling.rst, docs/beyond_basics/basics-specialpurpose.rst, docs/beyond_basics/intro.rst, docs/intro/intro.rst, docs/intro/windows.rst, docs/usecases/intro.rst
Fixes #1120 on the main branch. I will also push some changes on the book-intro branch.
=> make chapter deco figures images

docs/basics/101-105-install.rst, docs/basics/101-106-nesting.rst, docs/basics/101-110-run2.rst, docs/basics/101-115-symlinks.rst, docs/basics/101-116-sharelocal.rst, docs/basics/101-117-sharelocal2.rst, docs/basics/101-121-siblings.rst, docs/basics/101-122-config.rst, docs/basics/101-123-config2.rst, docs/basics/101-125-summary.rst, docs/basics/101-130-yodaproject.rst, docs/basics/101-135-help.rst, docs/basics/101-135-intro.rst, docs/basics/101-136-filesystem.rst, docs/basics/101-137-history.rst, docs/basics/101-139-gin.rst, docs/basics/101-139-hostingservices.rst, docs/basics/101-139-privacy.rst, docs/basics/101-146-gists.rst, docs/basics/topic/adjustedmode-unlockedfiles2.rst, docs/beyond_basics/101-168-dvc.rst, docs/beyond_basics/101-169-cluster.rst, docs/beyond_basics/101-179-gitignore.rst, docs/intro/filenaming.rst, docs/intro/howto.rst, docs/intro/narrative.rst, docs/usecases/collaborative_data_management.rst, docs/usecases/datastorage_for_institutions.rst, docs/usecases/reproducible-paper.rst, docs/usecases/supervision.rst
https://www.merriam-webster.com/grammar/cannot-vs-can-not-is-there-a-difference
=> 'can not' -> 'cannot'

docs/basics/101-116-sharelocal.rst
They do indeed never touch (as in modify), but I think in non-technical language "touch" has a more broad connotation.
=> Slightly more precise phrasing.

docs/basics/101-115-symlinks.rst
of a benefit for symlink based work tree.
=> Version switching is at least as important (if not more)

docs/basics/101-115-symlinks.rst
This helps when they start floating in the PDF.
=> Make some box titles more self-explanatory

docs/basics/101-101-create.rst, docs/basics/101-115-symlinks.rst, docs/basics/101-116-sharelocal.rst, docs/basics/101-123-config2.rst, docs/basics/101-130-yodaproject.rst, docs/basics/101-132-advancednesting.rst, docs/basics/101-133-containersrun.rst, docs/basics/101-136-filesystem.rst, docs/beyond_basics/101-146-providers.rst, docs/beyond_basics/101-147-riastores.rst, docs/beyond_basics/101-161-biganalyses.rst, docs/beyond_basics/101-179-gitignore.rst, docs/usecases/HCP_dataset.rst
to fix https://github.com/psychoinformatics-de/book-datalad-intro/issues/103
=> turn 'hidden section' references into find-out-more refs

docs/basics/101-115-symlinks.rst, docs/intro/windows.rst
=> integrate windows wit into previous section

docs/basics/101-136-filesystem.rst, docs/basics/101-137-history.rst, docs/basics/_examples/DL-101-136-168
as this changed on code block, it needs an appveyor run
=> small fixes in the file system section

docs/basics/101-138-sharethirdparty.rst, docs/basics/101-139-gin.rst, docs/basics/101-141-push.rst
=> Consistently write GIN all uppercase

docs/basics/101-121-siblings.rst
=> remove reference to removed output

docs/basics/101-117-sharelocal2.rst
=> be more precise in UUID wording

docs/basics/101-121-siblings.rst
=> make a footnote about the identical git identities

docs/basics/_examples/DL-101-117-101, docs/basics/_examples/DL-101-117-102
otherwise the text does not really make sense.
=> For these snippets we need to see a UUID

docs/basics/101-115-symlinks.rst, docs/basics/topic/adjustedmode-nosymlinks.rst, docs/glossary.rst
Explicit mention in box, new glossary term (and also one for 'corresponding branch'), plus minor updates for the 'adjusted branch' term.
Add a hint that this is not at all windows-only.
Closes #1136
=> Adjusted mode

docs/basics/101-115-symlinks.rst, docs/glossary.rst
Explicit term. More acurrate description, less focused on checksums only (there are checksum-less backends).
Closes #1132
=> On annex-keys

docs/basics/101-122-config.rst, docs/basics/101-123-config2.rst
@mih could you check if the .gitattributes description addresses https://github.com/datalad-handbook/book/issues/1166?
=> Configuration tweaks

docs/basics/101-115-symlinks.rst, docs/basics/topic/tree-symlinks.rst
Box linkage presently only works within-file. The approaximate description of a related ox was not good enough for me.
=> Re-import topic again, for better linkage

docs/usecases/openneuro.rst
=> Fix wrong command in open neuro quickstart

docs/index.rst
I think with a physical book out, it is time to remove the statement from the frontpage. The note is kept, though, because the spirit should stay the same.
=> No more beta

docs/basics/101-110-run2.rst
tiny bit to small => tiny bit too small
=> Fix spelling on 101-110-run2.rst

.zenodo.json
As suggested by @adswa in https://github.com/datalad-handbook/book/pull/1226#issuecomment-2200078287.
=> Add Matthias Riße to .zenodo.json

docs/basics/101-101-create.rst, docs/basics/101-105-install.rst, docs/basics/101-110-run2.rst
Just some minor fixes for things I noticed reading through the first and second chapter of "Basics".
=> Fixes for minor things I noticed while reading the handbook

.zenodo.json
Hi,
as suggested by @adswa.
Cheers + thanks,
Mika
=> add myself to zenodo.json

docs/basics/101-115-symlinks.rst
Hi, thank you for this great book.
I found a word repetition while reading.
=> delete repeated word 'more'

docs/basics/101-138-sharethirdparty.rst
It caused bookbuild failures: https://github.com/datalad-handbook/book/actions/runs/12561217632/job/35019747663
=> remove unreferenced footnote

.gitignore, .zenodo.json, docs/basics/101-116-sharelocal.rst, docs/basics/101-121-siblings.rst, docs/basics/101-123-config2.rst
fixed some smaller typos and a bigger one where a false path caused some confusion for me while reading the book.
=> Fix some typos

docs/basics/101-123-config2.rst
=> FIX: typo in largefiles annex config

docs/beyond_basics/101-169-cluster.rst
Hey,
in the meanwhile, there are a few more versions available via EasyBuild, so I made the description a bit more generic.
=> update EasyBuild Info
