.travis.yml, Makefile, docs/conf.py, docs/contents.rst.inc, docs/remove/_examples/firstdemo, docs/remove/_examples/seconddemo, docs/remove/me.rst, requirements.txt
This adds a new chapter "remove" to demonstrate the use of a custom sphinx extension to run arbitrary (shell) code and capture the output. The goal is to be able to auto-execute real examples, but capture and cache their output for inclusion in the book, without having to run all code at build-time.
Here is the extension:
https://github.com/mih/autorunrecord
It should be pip-installable: `pip install autorunrecord`
The rest should be automatic.
The `runrecord` directive shown in the examples can be used in the same fashion and has the same features as the `literalinclude` directive that comes with sphinx (in fact, it is based on it). In addition, however, it can auto-generate the to-be-included files based on the code given in the block. Moreover, if it is necessary (e.g. for didactic …
=> [WIP] Test of using a sphinx extension for auto-recorded examples

docs/_static/custom.css, docs/_templates/page.html, docs/conf.py, docs/contents.rst.inc, docs/remove/metoo.rst
Upfront: I followed advice from someone on the internet, and I'm not sure whether what I'm doing could interfere with other things. Maybe @mih can have a look at this.
When writing sections I'm torn between keeping everything simple and short, and including very useful, but more advanced information that would make the content of a page appear more complex than it actually is. Such more advanced options would fit content-wise, and would be helpful for readers that want to learn more or are already more proficient, but could be intimidating, frustrating or needlessly complex for very new users.
One potential solution I thought about is having folded sections that one can unfold on demand (a bit like the ``<details> </details>`` functions in Github markdown). With this PR, I'm trying to …
=> Foldable sections on pages

.travis.yml
This causes the tests to run for much longer (big Latex toolchain download), but still <5min -- I think it is worth it.
=> Also build the PDF version as part of the continuous integration tests

.travis.yml, docs/conf.py, docs/contents.rst.inc, docs/remove/uml.rst, requirements.txt
On Debian: `sudo apt-get install plantuml`
Redo: `pip install -r requirements.txt`
Demo page is included, many many more examples at http://plantuml.com
Rendered demo page: http://handbook.datalad.org/en/helpers/remove/uml.html (not all types are supported by the version on readthedocs).
=> PlantUML support for crazy-flexible plain-text diagrams

docs/index.rst
simple ``important`` directive to inform accidental visitors about the state of things on the frontpage (see #57).
=> add front page info on alpha stage, fixes #57

docs/conf.py
With the updated feedback after #62 noted in #61, this also adds links to the previous and next section at the bottom of the page.
=> add bottom page section links as well, fixes #61

docs/basics/101-105-install.rst, docs/basics/101-107-summary.rst, docs/basics/_examples/DL-101-105-106
Getting rid of all ``datalad status --annex basic`` in response to #74.
=> dl st --annex basic -> dl st --annex, fixes #74

docs/basics/101-109-rerun.rst, docs/basics/_examples/DL-101-108-110
use ``>| `` instead of ``>`` to overwrite existing files.Thanks to Alex for this advice!
=> shell-agnostic pipe

docs/basics/101-101-create.rst
Failure might have been resolved with Sphinx>2 dependency change before.
This reverts commit 5030564327e048ce80fd5d5cbb009e5dedb72d67.
=> Revert "Readthedocs build crashes (due to missing section number?)"

docs/basics/101-102-populate.rst
I gave a short Datalad intro based on the book today at the Neurohackademy. I realized that many Mac users did not by default had Unix tools my Debian system had, so I added footnotes about them.
=> add note on unix tools not preinstalled in OSX

docs/_static/custom.css, docs/basics/101-102-populate.rst, docs/basics/101-105-install.rst, docs/basics/101-108-run.rst, docs/basics/101-110-run2.rst, docs/basics/101-111-run3.rst, docs/basics/101-115-symlinks.rst, docs/basics/101-121-siblings.rst
This makes the "additional sections" in Sphinx containers a bit more visible. I added border and background, exchanged the unicode arrow, and adjusted existing headers to not be completely bold (as salience with color hopefully suffices).
Its by no means what we want to have for the future (#109), but in principle a bit better than what we currently have.
=> Slightly less crappy toggle containers

docs/basics/_examples/DL-101-125-109, docs/basics/_examples/DL-101-125-110, docs/basics/_examples/DL-101-125-111, docs/basics/_examples/DL-101-125-112
#104 missed some example files. I don't know why the build didn't fail, to be honest. As far as I can see, there are no other example files with these names in this repository (``_examples/DL-101-125-109``  - ``_examples/DL-101-125-112``). The rendered version included really funky examples instead of failing. For example:
```
$ datalad status
bash: line 1: datalad: command not found
```
or a git diff displays the ``docs/conf.py`` contents:
```
$ git diff
diff --git a/docs/conf.py b/docs/conf.py
index 19b18d8..7890263 100644
--- a/docs/conf.py
+++ b/docs/conf.py
@@ -310,3 +310,180 @@ plantuml_latex_output_format = 'pdf'
def setup(app):
app.add_stylesheet('custom.css')
+
+
+
+
+###########################################################################
+#          auto-created …
```
=> add yet missing example files

dataladhandbook_support/directives.py, docs/basics/101-125-config.rst
Visual impression should be unchanged from status quo. But now we have it semantically marked-up and can distinguish it from other boxes and toggle containers.
=> 'findoutmore' RST directive, plus exemplary use

docs/basics/101-102-populate.rst, docs/contributing.rst, docs/intro/narrative.rst
I gave the rendered book a quick read and fixed some problems:
- a left-over "linktocontributing"
- an accidental linebreak in the text
- I added a link to download the ProGit book just as for the other books, to give an alternative to running ``wget``
- a missing file extensions in ``pip install requirements`` on the contributing page
=> More obvious bugs in the book

docs/_static/custom.css, docs/_templates/sidebarintro.html
As noted by @effigies in #170 (thanks!), content in the sidebar can be invisible, for example when zooming in too much. This is both because a larg-ish empty box makes it taller than the page, and because the side bar is fixed.
In principle, I like the space in the sidebar because it creates a nice visual offset between the intro in the sidebar and the Contributors section, making both parts more striking/visible. I'd also like to have the sidebar fixed in the sense that scrolling the main content does not scroll the sidebar away, because it keeps the navigation links to the landing page, pre-/succeeding sections, Github, and the quicksearch close by in very long sections. 
In this PR I therefore try to mitigate the problem by
- decreasing the amount of white space between intro and …
=> Improve sidebar experience, fixes #170

docs/intro/installation.rst
Based on the description in #177 , this adds a short, toggled container with instructions for non-root access Linux machine. We can keep it open for potential adjustments if more comes out of #177.
=> add nonroot linux installation

.all-contributorsrc
This fixes #200 by giving @lisanmo her full name. While I was at it I also included my second name's initial.
=> handpolish more contributor names, fixes #200

.travis.yml, docs/conf.py
This lets the PDF use fonts that are closer to what readthedoc's theme uses. It's pure personal taste - I find those fonts more readable and more modern, but I'm also happy to stick to the defaults.
=> adjust latex fonts to resemble those of readthedocs

docs/intro/installation.rst
This should finally get the installation instructions into a complete-ish state:
- updates Windows native installation instructions with Miniconda (using notes from https://github.com/datalad-handbook/book/issues/132) and make it the default
- add WSL2 instructions from issue for completeness (based on notes in https://github.com/datalad-handbook/book/issues/114)
- removes todos
- add "eg HPC systems" to Linux machines with no root access
Question to @mih: 
- You briefly mentioned enabling SSH Server via powershell yesterday. Am I right in my assumption that this is not necessary for a user-installation (but rather to use ``bnbdatalad``, see https://github.com/psychoinformatics-de/org/issues/91)?
- You once mentioned https://tortoisegit.org/ as an alternative, what do you think about this …
=> finalize installation section

docs/index.rst, docs/intro/installation.rst
- Note that the Miniconda-based installation on DataLad only provides 0.11; add instructions how to upgrade (based on [this question](https://neurostars.org/t/datalad-install-datalad-containers-extension-in-conjunction-with-singularity-datalad-container/5246) mentioned in https://github.com/datalad-handbook/book/issues/177#issuecomment-542872693)
- Remove "future release" from note on landing page
=> Add installation notes

docs/intro/installation.rst
This warns about 0.12 being not yet available via most package managers, and guides users to install the most recent release candidate with pip- or conda-based methods.
I have also placed the instructions for non-root access Linux machines outside of a toggle-able container.
=> On DataLad versions in installation instructions

docs/basics/101-105-install.rst, docs/basics/101-115-symlinks.rst
@loj and @bpoldrack discovered that OSX Finder was not able to
display broken symlinks, essentially hiding available files.
This should make readers aware in the section installing datasets,
and give some more information on this in the section on symlinks
=> warn about invisible broken symlinks in certain viewers

Makefile, docs/usecases/datasets.rst
This separates removing examples and workdirs for usecases from removing examples and workdirs for the rest of the book. With a growing amount of use cases, it will take more and more time to compute them, while recomputing them is not relevant (they are standalone), especially not for the basics sections of the book.
Performance observation:
``Make`` with removed examples from intro, basics, and usecases
``73.52s user 17.27s system 56% cpu 2:40.54 total``
``Make`` with removed examples from intro, basics
``38.38s user 11.66s system 67% cpu 1:13.68 total``
=> Slim makefile, fixes #218

docs/glossary.rst, docs/intro/installation.rst
This fixes #236 -- while troubleshooting a failed datalad installation on OSX 10.14 (Mojave) via ``pip install datalad`` we found that the default preinstalled Python package manager was ``pip3``.
=> Refine install instructions for OSX

docs/basics/101-127-procedures.rst
This fixes #212 by adding a hidden section that mentions that the superdataset will report a subds as being "modified" once a procedure is applied to this subdataset. On a more general level, though, this shows that we need a "advanced dataset nesting" section on how a heavily nested dataset behaves. This could be in conjunction with general notes on ``--dataset`` and ``--recursive`` options of commands.
=> add findoutmore on procedures in subdatasets

docs/_templates/page.html, docs/_templates/sidebarlogo.html
After #193 I looked a bit into "scrolling progress bars". This isn't yet what @lisanmo suggests (it's only page-wise) and I'm not sure yet whether or how one could get a chapter-wise progress bar in the HTML version of the book, but I will continue exploring. This is how it currently looks like (The blue bar progresses the more you scroll):
=> Page-wise progress bars

docs/basics/101-101-create.rst, docs/basics/101-102-populate.rst, docs/basics/101-103-modify.rst, docs/basics/101-105-install.rst, docs/basics/101-106-nesting.rst, docs/basics/101-108-run.rst, docs/basics/101-109-rerun.rst, docs/basics/101-110-run2.rst, docs/basics/101-112-run4.rst, docs/basics/101-114-txt2git.rst, docs/basics/101-115-symlinks.rst, docs/basics/101-116-sharelocal.rst, docs/basics/101-117-sharelocal2.rst, docs/basics/101-118-sharelocal3.rst, docs/basics/101-119-sharelocal4.rst, docs/basics/101-121-siblings.rst, docs/basics/101-140-filesystem.rst, docs/contributing.rst, requirements.txt
This fixes #246, but it relies on https://github.com/mih/autorunrecord/pull/3 being merged first, and a subsequent update of ``requirements.txt`` to the latest version of ``autorunrecord``.
=> Do not render speakernotes as captions

docs/_templates/sidebarintro.html
Plus slight change of link text style
=> Add frontpage link to github repoof handbook

Makefile
Following #224, this adds a general ``make clean`` that gets rid of all examples and workdirs.
=> add general clean target to Makefile

docs/basics/101-114-txt2git.rst
This adds a simplified graphic how git versus git-annex with regard to content-locked files.
=> Simplified overview on content lock with git-annex

docs/intro/installation.rst
This adds instructions on how to use brew to install Git-annex. Thanks to @NevenaK for bringing this to our attention!
@all-contributors, please add @NevenaK for userTesting!
=> brew based installation of git-annex for mac

docs/basics/101-130-yodaproject.rst, docs/code_from_chapters/10_yoda_code.rst, docs/contents.rst.inc
This can create a minimal YODA project example. The assortment of code snippets used consists of the following:
- Create ``midterm_project`` as a yoda-configured subdataset of DataLad-101
- Install the iris dataset as a subdataset
- Prepare a simple data analysis script
- Perform the analysis with ``datalad run``
- Add a human readable description
I am planning to use this cast in the Workshop in Aachen next week (see https://github.com/datalad-handbook/course/issues/18)
=> prepare minimal, functional cast on yoda project

docs/glossary.rst, docs/intro/installation.rst
This is yet another addition the the installation page. Specifically, it advises how to add locations that are not on ``$PATH`` after installation via ``pip3 install --user ...`` to the ``PATH``.
=> Advice on ``PATH`` for macOS installation

docs/_static/custom.css, docs/conf.py
This inches towards #38. A main deficiency of the PDF is that the colored admonition boxes are not preserved. Instead, notes or other directives that are not codeblocks are simply distinguished from normal text by a bit of spacing and table lines(?). This adds almost-DataLad-colored boxes around Note and Important directives (haven't figured out a general Admonition role yet...)
**Before**:
**After**:
This needs further work (e.g., also TODOs are now brightly orange), but its a start
=> DataLad Colors

docs/intro/philosophy.rst
The section ends with the paragraph "_But enough of the abstract talking. You came here to learn, and the handbook will not waste your time further by requiring you to only read – let’s start to use DataLad._"
However, the next section is "How to use the handbook". I suggest removing this pargraph, or moving it to the "How to use the handbook" section.
=> Minor sentence and typo fixing

.zenodo.json
Note that adding access_right open also makes "license" field required
https://developers.zenodo.org/#representation
=> ENH: added zenodo entry for myself, unified some affiliations, added access_right field

docs/_templates/sidebarintro.html, docs/basics/101-135-help.rst, docs/basics/101-135-intro.rst, docs/basics/101-137-history.rst, docs/basics/101-179-gitignore.rst, docs/code_from_chapters/intro.rst, docs/contents.rst.inc
This attempts a clearer structure in the later sections of the book.
- FAQs are moved to Appendix, and linked in sidebar
- Code snippet lists have their own section and are moved out of the appendix
- The chapter "Help yourself" is reordered and has a short intro now
=> Tweaks to the structure of the later sections and chapter

docs/basics/101-101-create.rst, docs/contents.rst.inc, docs/contributing.rst, docs/index.rst, docs/intro/executive_summary.rst, docs/intro/installation.rst, docs/intro/narrative.rst, docs/intro/philosophy.rst, docs/teaching.rst
This introduces changes to the first parts of the book:
- I'm removing the alpha stage note on the front page, and replace it with a short introduction of the aims of the handbook as stated in our abstract
- A few tweaks to some introductory sections to connect them better, define the scope, a bit of restructuring, ...
- Adding a ``Teaching with the DataLad Handbook`` section that points to the educational resources for trainers we provide
=> Improve flow of Introduction and a few adjustments with regard to the OHBM abstract

docs/basics/101-108-run.rst, docs/basics/101-114-txt2git.rst, docs/basics/101-116-sharelocal.rst, docs/basics/101-130-yodaproject.rst, docs/basics/101-135-help.rst, docs/basics/101-137-history.rst, docs/contributing.rst, docs/intro/installation.rst, docs/intro/narrative.rst
I'm adding illustrations proposed [here](https://github.com/datalad-handbook/artwork/pull/2)
=> Adding some illustrations

docs/basics/101-102-populate.rst, docs/basics/101-132-advancednesting.rst, docs/basics/101-137-history.rst, docs/basics/_examples/DL-101-102-112, docs/basics/_examples/DL-101-132-110, docs/basics/_examples/DL-101-137-142
Not a problem for the handbook build, but executing the full command in the terminal when copied from the book will not work.
=> Fix code that works to build the book but not when copied

docs/basics/intro.rst, docs/contents.rst.inc, docs/usecases/intro.rst
This adds a hidden page between "Introduction" and "Basics" and between "Basics" and "Usecases". They are hidden in the toctree, but readers can get to them if they navigate from section to section with the side bar navigation.
These intermediate pages should notify readers that they are transitioning from one part of the book to another, which is particularly helpful between Basics and Usecases, since there is no clear "The Basics end here" in the at this point last Basics section.
=> Hidden index pages between sections

docs/conf.py
The change in this PR ensures that @mih will always stay the last author of the book in the PDF version.
=> always append mih as last author to list of authors

docs/basics/101-136-filesystem.rst, docs/basics/101-137-history.rst, docs/basics/_examples/DL-101-136-147, docs/basics/_examples/DL-101-136-148, docs/basics/_examples/DL-101-136-149
This closes #303. I have added a paragraph on ``git annex unlock``, and how to get previously annexed contents stored in Git.
=> Mention git annex unannex

.zenodo.json
- There were two commas that invalidated the json file
- Removed creators versus contributors distinction to put mih at the bottom to be last author
[jsonlint](https://jsonlint.com/) says its valid json, and authorship is fixed to Wagner, A. S. ... & Hanke, M.
=> restructure and fix zenodo

.zenodo.json
Previous zenodo archival attempts failed, 'https://developers.zenodo.org/#representation' hints at
wrong meta data information about upload types
=> attempt correct meta data descriptors

docs/basics/101-136-cheatsheet.rst
This fixes #360. 
I have pushed updates to the submodules Makefile that render a separate, page-wise plain .svg version with all text being converted to paths (to prevent browser-dependent appearance of the fonts used in the .svg). With this PR, the cheatsheet preview links to this new file.
=> Cheatsheetfix

docs/conf.py, docs/contents.rst.inc, docs/intro/philosophy.rst
- ~remove URLs in Footnotes. We can rely on the href'ed text~
- Colored subheadings in more DataLad-dy color scheme, code boxes. TODO directives are not brightly orange anymore, but framed between slim orange bars
- Enforce figure positions in the text. This places the figures where they need to be, and prevents empty pages surrounding a single figure on an additional otherwise empty page.
- remove blank pages after toctrees and after headings (-> 50 pages fewer).
=> Further Latex improvements

docs/contents.rst.inc, docs/intro/philosophy.rst, docs/usecases/intro.rst
Whether or not we will go forward with https://github.com/datalad/datalad/pull/4046#issuecomment-575920252, this restructures the toctree:
- Use cases are numbered (I went for roman numbers, but that's an arbitrary choice made for slightly better distinction to the Basics numbering) and get short, general headings
- Each use case gets a short description in the toctree
- Small figures separate major parts of the book (Intro-Basics, Basics-Usecases)
I think this makes the use cases more visible. 
TODO:
=> Restructure usecases

requirements.txt, setup.py
Was trying to build https://github.com/brainhack-princeton/handbook which is based on the datalad-handbook "setup" to run into
```
unsupported theme option 'show_relbar_bottom' given
```
According to https://alabaster.readthedocs.io/en/latest/changelog.html it seems was added in 0.7.11 so added versioned dependency.  I am not 100% sure on either changes to setup.py are due, or they should be restricted solely to the dependencies of the `dataladhandbook_support/`, if so -- just CP bf071c5e3613e13c093639829dfba765785871ed and abandon the other commit/PR.
Cheers
=> BF: alabaster version

docs/basics/101-130-yodaproject.rst
After exploring the difference in path interpretations across Python functions I thought it would be useful  briefly mention how information about the dataset a command should operate on can be passed to Python functions.
I'm also adding a note that using dataset methods or specifying the ``dataset=`` argument with a Dataset instance (as opposed to a string) yields more consistent behavior.
=> The dataset argument in python functions

.readthedocs.yml, requirements.txt
ATM we don't have a readthedocs.yml file, and Readthedocs builds the handbook with the most recent Sphinx release (2.3.1). I believe that this version leads to a tiny bug, described in #379. By pinning Sphinx to an earlier version in ``requirements.txt`` and providing a ``readthedocs.yml`` file, I hope to get rid of the broken meta property tag.
Hopefully fixes #379.
=> Pin Sphinx version for readthedocs to prevent #379

docs/basics/101-144-intro_extensions.rst
- crawler (the cradle of DataLad AFAIK) was left behind :-(  It could be an ugly old duckling ATM, but IMHO still worth mentioning.
- `pip` is one way to install.  
Installation chapter already introduces to `conda` etc.  So I think it is worthwhile at least mentioning that extensions might also be available from originally used distribution.
I also expect https://github.com/datalad/datalad-extensions (or later some gh-pages view of it) will be improved to provide an overview of their status etc.
=> ENH: extensions - add crawler and mention that they might be available "natively"

dataladhandbook_support/directives.py, docs/conf.py
I'm trying to inch closer towards distinguishing gitusernotes and findoutmores in the PDF output.
With the current changes I can get something like this for the Gitusernote (somewhat arbitrary color
choices):
Yet to succeed for the Findoutmores...
=> Colored boxes around gitusernotes

docs/conf.py
This sets ``'DATALAD_UI_PROGRESSBAR': 'none',`` to fix #390.
=> bf: configure no progress bars to prevent #390

.readthedocs.yml
I suspect a previous failure in #399 was due to this
=> bf/tmp: explicitly include submodules.

docs/basics/101-135-help.rst, docs/glossary.rst, docs/intro/installation.rst
This attempts to collect, explain, and show strategies to solve common errors or warnings. It will forever be work in progress, so just as with FAQ, I'm happy to merge the developments in this branch whenever something useful gets added.
=> Start to work on concrete examples of warnings or error messages in help section

docs/basics/101-124-procedures.rst, docs/basics/101-136-cheatsheet.rst, docs/intro/executive_summary.rst
This is all untested, as I did not build the handbook (the build system scares me ;-). So all file paths are where I assume the files are.
This PR:
* normalizes the spelling of cheat sheet (all forms used were valid; but it should be consistent)
* fix the preview image for the cheat sheet (pdf is not recognized by browsers as an image type)
* simplifies the link to the PDF, so the user doesn't end up on GitHub having to click "download" to get the PDF.
This PR took the conservative approach and simplifies the process from 3 steps to 2 when acquiring the cheat sheet. If you don't have plans to add content to the cheat sheet webpage, you could  remove it entirely and just link to the cheat sheet directly, reducing the steps to 1.
=> fix cheat sheet link and preview

docs/conf.py, requirements.txt
A first try to use the page-not-found extension. Its a slight shot in the dark, there is no way to preview the outcome:
> If you open the 404.html file on the browser, you will see that all of the images and css does not display properly. This is because all the URLs are absolute and since the file is being rendered from file:// in the browser, it does not know where to find those resources.
> Do not worry too much about this, this is the expected behavior and those resources will appear once the docs are deployed.
=> add sphinx-notfound-page to the requirements

docs/basics/101-127-yoda.rst, docs/basics/101-130-yodaproject.rst, docs/basics/101-134-summary.rst, docs/basics/101-138-sharethirdparty.rst, docs/basics/101-139-gin.rst, docs/basics/101-141-push.rst, docs/basics/_examples/DL-101-141-101, docs/basics/basics8toc.rst, docs/basics/basics9toc.rst, docs/glossary.rst
This sits on top of #412 and adds a standalone section to elaborate on and wrap up the details of ``datalad push``.
This fixes #281.
=> Standalone section on push

docs/intro/installation.rst
This a convenience PR to remove WSL installation instructions, should we decide to do so.
Fixes #382, fixes #114, fixes #110.
=> WSL: remove installation instruction for Windows subsystem for Linux

docs/intro/installation.rst
This links to the rpm git-annex-standalone linked in
#434, and also suggests a conda-based installation.
fixes #434.
=> add installation instructions for rpm based linux distributions

docs/basics/101-146-providers.rst, docs/basics/basics10toc.rst
This is quickly written down and without much substance to it (quite difficult to dig through the docstring-less ``downloaders`` code base). If it contains too many errors, we can add the XNAT configuration as a gist for now and wait until I know more about file transfer and credential management.
=> Add a short initial section on configuring providers

docs/basics/101-138-sharethirdparty.rst, docs/basics/101-139-gin.rst, docs/basics/_examples/DL-101-139-107
This updates the third party sharing chapter with Gin's new ability to allow anonymous read-only access to datasets. I have also pointed out more prominently that Gin is an easy alternative to other third party services in the first section by transforming it into a note, but please weigh in on whether we may want to rewrite the section on Gin to become the first section in this chapter.
@achilleas-k, if you have links to cross-reference to your docs, or any general feedback, let me know!
=> Data sharing via Gin -- Update

docs/basics/101-135-help.rst
- Add receive.denyCurrentBranch configuration  as an alternative to enable pushing to non-bare repositories
=> More warning/error messages/hints to help

docs/basics/101-112-run4.rst
This adds a small note on ``--explicit`` and `run`, and results from the fact that until now I wasn't aware that simply appending an ``--explicit`` to a `datalad run ...` is not possible.
=> Run: mention that the command needs to be the last element of a run call

docs/usecases/datastorage_for_institutions.rst
They may work, but they aren't needed.
=> BF: Remove superfluous colons from URLs

docs/index.rst, docs/intro/installation.rst
This adds installation and configuration instructions for the JSC to the installation section of the INM-7 version of the handbook.
=> installation on JSC infrastructure

docs/basics/101-141-push.rst
As described in #481, the previous description of how push
behaves in datasets with multiple branches was inaccurate,
and resulted from my explorations of push with an explicitly
configured dataset. This change rectifies this, and instead
shows how to configure datasets such that more than just the
current branch is pushed. Fixes #481.
I would appreciate if someone could double check. :)
=> BF: Replace inaccurate description of push behavior

dataladhandbook_support/directives.py, docs/_static/custom.css, docs/conf.py, docs/intro/narrative.rst
This leaves the general structure unchanges, but all styling is done in Latex or CSS, without changing the docutil node structure anymore.
For the PDF switch to tcolorbox for more beautiful boxes that can span multiple pages. Also use "DataLad colors" more intensively.
=> Do not use docutil nodes for markup purposes, more beautiful boxes

docs/conf.py
First, it makes sense to targeted two-sided printing at 400+ pages, and
second it removed tons of warnings from the PDF build, because it
removes a conflict between sphinx's fancyhdr setup, and our previous
explicit 'oneside' configuration.
=> Build two-sided PDF

README.md
The bot stopped counting contributors. This implements a fix according to https://allcontributors.org/docs/en/bot/faq#all-contributors-badge-count-does-not-update.
Fixes #541
=> BF: fix allcontributors counting

README.md
next attempt after #542 failed. Background: https://allcontributors.org/docs/en/bot/faq#all-contributors-badge-count-does-not-update
Also adds an updated contributor count
=> BF: fix all contributors count

docs/basics/101-123-config2.rst, docs/basics/101-135-help.rst, docs/basics/_examples/DL-101-135-105, docs/glossary.rst
Fixes #536.
Feedback welcome. At the moment, this is an overview of logging and a hint on how to get into the debugger, and a collection of funny comics to make reading the section less dreadful :wink:
Also, I found https://github.com/datalad/datalad/issues/4661 while at it.
=> How to debug/troubleshoot

docs/intro/installation.rst
Mentions 7zip/p7zip as a potential dependency and adds a note about installing it in every installation
section where it is not automatically installed (pip, macOS). Fixes #572.
=> Install: Mention 7zip dependency when its not automatically installed

docs/_static/cheatsheet.svg, docs/_static/gist.svg, docs/_templates/sidebarintro.html
Adds a cheatsheet button and a button "Get the gist" that links to the one-page-summary in the intro.
=> Add shortcut buttons to cheatsheet and summary to sidebar

docs/basics/101-180-FAQ.rst, docs/index.rst, docs/r.rst, docs/usecases/openneuro.rst
This adds a section to the appendix that serves as a "Quick start guide" for OpenNeuro users,
=> OpenNeuro quick start guide

docs/basics/101-133-containersrun.rst, docs/basics/_examples/DL-101-133-101, docs/basics/_examples/DL-101-133-102, docs/basics/_examples/DL-101-133-103, docs/beyond_basics/_examples/DL-101-147-111, docs/code_from_chapters/10_yoda_code.rst, docs/code_from_chapters/OHBM.rst
The previous container was a year old with git-annex 7.x and ran into issues in
v8 annex repositories. This change replaces code pointing to the previous image with code pointing to the new one.
This doesn't feel like the most clean way to do things, though. Is there a way to add a ``latest`` tag to the most recent image and change the code to pull the image via this tag?
=> MNT: Update singularity image for midterm analysis to latest version

docs/basics/101-130-yodaproject.rst
I keep getting more and more urgent sounding deprecation notices when using ``userpassword`` authentication to GitHub. The handbook should encourage token-based authentication more.
=> GH-auth: more explanation on how to get a GitHub token

.zenodo.json, docs/basics/101-115-symlinks.rst, docs/basics/101-133-containersrun.rst, docs/beyond_basics/101-161-biganalyses.rst
Fix issue #593 
- Fix 2 typos
- Add a comment in Chapter 3.2 for md5 checksum in macOS
- Add a note in Chapter 7.2 to remind user to install `datalad-container` first
=> Minor typo and other feedback on the INM7 version

docs/basics/101-180-FAQ.rst
After a quick chat with Adina
Draft PR about details on copying locked data out of a data set.
The files you get only have "read" access and users might not be aware of that.
=> FAQ: add details on copying locked files out of dataset

docs/beyond_basics/101-171-enki.rst
There was an error in the ENKI preproc workflow script that presumably was fixed in the most recent version of the workflow file. It made it into the handbook because I wrote this section when this fix wasn't yet introduced. @mih, I would consider this a hotfix.
=> BF: Fix a trailing slash in the script

docs/basics/101-101-create.rst, docs/basics/101-102-populate.rst, docs/basics/101-103-modify.rst, docs/basics/101-105-install.rst, docs/basics/101-108-run.rst, docs/basics/101-109-rerun.rst, docs/basics/101-110-run2.rst, docs/basics/101-114-txt2git.rst, docs/basics/101-115-symlinks.rst, docs/basics/101-121-siblings.rst, docs/basics/101-123-config2.rst, docs/basics/101-130-yodaproject.rst, docs/code_from_chapters/usecase_ml_code.rst, docs/glossary.rst, docs/index.rst, docs/intro/installation.rst, docs/intro/windows.rst
I'm working my way through the handbook on Windows and add "Windows-Workaround" Sections where ever necessary. So far, its frequently necessary.
=> Towards more user-friendliness for Windows Users

docs/basics/101-130-yodaproject.rst, docs/usecases/reproducible-paper.rst
Hey @mih, I have created a template for writing a reproducible paper mirroring what we have described in the reproducible paper usecase. I did it for the Workshop next week, but its probably nice to have it mentioned in the relevant handbook sections, too. You can find the template at https://github.com/datalad-handbook/repro-paper-sketch/. @m-wierzba is also taking a look at it for feedback :)
=> Repro Paper: mention template in relevant sections

docs/r.rst
cc @yarikoptic.
This allows you to reference http://handbook.datalad.org/en/latest/basics/101-138-sharethirdparty.html#use-github-for-sharing-content with "handbook.datalad.org/r.html?LFS". Is that what you had in mind?
=> REF: add permalink for Git LFS section

docs/basics/101-130-yodaproject.rst
This change comes in response to @yarikoptic's PR https://github.com/datalad/datalad/pull/5218 that removes ``create-sibling-github``'s ``--github-psswd`` argument.
It adds a note about GitHub's deprecation of User-Password authentication, mentions the removal of the option starting with ``0.14.0`` (correct?), and explains ways to store/supply the oauth access token.
=> MNT: adjust for user-passwort deprecation of GitHub

docs/usecases/HCP_dataset.rst
Closes #620 
Thank you @adswa for your feedback on my original issue. I've made some changes using the markup you suggested there. Should I also document the other alternatives you mentioned (eg. modifying `keyring_pass.cfg` or setting environment variables)? Or do you think this solution would cover most people's computers?
=> add instructions to reset AWS keys when downloading HCP data

docs/basics/101-122-config.rst, docs/basics/101-123-config2.rst, docs/basics/101-124-procedures.rst, docs/basics/101-125-summary.rst
- make it clear that git and git-annex will not query .datalad/config for configurations
- point out procedures as an explicit alternative
- minor formatting and windows adjustments
in response to https://github.com/datalad/datalad/issues/5217
=> Disambiguations in the configuration sections

Makefile, docs/basics/101-124-procedures.rst, docs/beyond_basics/101-168-dvc.rst, docs/beyond_basics/_examples/DL-101-168-102a, docs/beyond_basics/_examples/DL-101-168-102b
A first set of adjustments that are necessary for convincing the CI setup to work.
This set of changes mainly deals with the DVC chapter.
First off all, I remove it from the clean-examples target. clean-examples thus wipes out everything in Basics and Advances but the DVC chapter. This is because it takes very long to build, and it already has its own target (clean-DVC).
Secondly, it uses a local push target instead of a GitHub remote. This is necessary so that building locally on remote CI machines succeeds. For a similar reason, cloning within the DVC chapter uses now https instead of SSH.
=> Workflowtest adjustments

docs/beyond_basics/101-147-riastores.rst
In the upcoming 0.14 release --no-storage-sibling is deprecated in
favor of --storage-sibling=off.
---
I don't recall where you landed on managing content for different DataLad releases.  I'd imagine at the least you'll need to hold off on this a bit, but perhaps the text should be reworked to mention both options for compatibility with earlier releases.
=> riastores: Avoid deprecated --no-storage-sibling

docs/intro/installation.rst
Would you mind reviewing this, @Remi-Gau? I tried to add installation instructions for Python 3 based on your pointers and thoughts in #649. :)
=> Python installation instructions

dataladhandbook_support/directives.py, docs/conf.py
- enable future display of box listings (by type)
Note that such a listing is not actually generated in this PR, only the prerequisites are established. A related, but unaddressed, topic is the numbering of boxes and their in-text referencing. This would be most helpful in the PDF to make box positioning more flexible.
=> Further streamlining boxes

dataladhandbook_support/directives.py, docs/conf.py
Works in HTML and Latex.
The reference a box, simply give it a name and use that one:
```rst
.. windowsworkarounds:: Funky instructions
:name: funky
can be referenced with :ref:`some in-text description <funky>`
```
=> Numbered, listable and referencable boxes

dataladhandbook_support/directives.py
By default all boxes are included at the location the appear in the
text. Optionally, (large) boxes be turned into float, like this:
```rst
.. windowsworkarounds:: For Windows users only
:float: p
```
where `p` is an (optional) positioning argument (the usual LaTex kind,
i.e. could also be something like `tbp`). If the position label is not
given (i.e. just `:float:`) LaTex will do its default thing.
Floating boxes likely will need to be referenced in the text, hence
should also come with a `name` attribute:
```rst
.. windowsworkarounds:: For Windows users only
:name: funky
:float: p
```
This change has no implications for the HTML output.
=> Optional float mode for PDF boxes

docs/basics/101-135-help.rst
This is a first demo of how it could be done. Essentially given sphinx a dedicated clue via `tabularcolumns` instead of having it guess.
https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-tabularcolumns
It is using the sphinx-specifc `\Y` column width specifier that should work across all table type we need (sphinx is switching type a lot, depending on table content).
Before:
Now:
More general table beautifications are coming, but this kind must be done per each table.
=> No vertical lines in a table

docs/basics/101-130-yodaproject.rst, docs/basics/101-137-history.rst, docs/basics/101-139-gin.rst, docs/conf.py, docs/usecases/reproducible-paper.rst
Not much (yet), but the removal of `H` needed unnesting of floats to get
it too compile. This is done here.
=> Let figures and tables float.

docs/conf.py
No indent on first line, to save some space for URL-type footnotes
=> Tune footnotes

docs/book_appendix.rst, docs/intro/installation.rst
Incorporating the latest wisdom and helpers.
The principle idea is to go from specific to generic, in order to let
readers with less expertise find working solutions more quickly, while
not hiding alternatives with better system-integration potential for
more experienced users.
Fixes #677 
@yarikoptic @jwodder If you have advice on what to do differently, please let me know.
=> Refurbish installation instructions

docs/r.rst
The Go-big chapter reference accidentally linked to the git-lfs section, and vice versa.
=> BF: Fix a mixed up redirection couple

docs/conf.py, docs/glossary.rst, docs/intro/narrative.rst
And explain them (latex output only).
=> Make term references accessible in the printed handbook

docs/basics/101-124-procedures.rst
Quotes encompassing values in git config files (including
.datalad/config), are not required and in fact inconsequential when
being read again via git-config. Showing them when displaying such
configs in the handbook may therefore be confusing and leading to the
user trying to achieve this, which is not possible via git-config or
datalad's python API. This would only be achievable by editing the raw
config file w/o a sanitizing interface.
Simply remove the depiction of such quotes, as I think debating this
aspect only makes the impression that it is somehow important, when
really these quotes have no effect at all.
(Closes #688)
=> Remove quotes from config file displays

docs/usecases/openneuro.rst
Fixes #687 by explaining how to clone legacy datasets from openfMRI.
=> On cloning openneuro/openfmri data from the datalad superdataset

docs/basics/101-105-install.rst, docs/basics/101-107-summary.rst, docs/basics/101-116-sharelocal.rst, docs/basics/101-130-yodaproject.rst, docs/basics/101-138-sharethirdparty.rst, docs/basics/101-139-gin.rst, docs/basics/101-141-push.rst, docs/basics/101-146-gists.rst, docs/beyond_basics/101-147-riastores.rst, docs/beyond_basics/101-148-clonepriority.rst, docs/beyond_basics/101-168-dvc.rst, docs/usecases/collaborative_data_management.rst, docs/usecases/datastorage_for_institutions.rst
I am going through the book, annotating different pieces (like individual commands) with index markup, such that content in the sections with narrative become more accessible to readers that do not (intent to) consume the whole book.
This PR could grow big. But there is not need to make it anyhow complete first. It could be merged (repeatedly) whenever it makes sense.
=> Make the index more comprehensive

docs/basics/101-130-yodaproject.rst
- Fixes typo to correct the ref tag
- Changes `find-out-more` to `Findoutmore` to be consistent with use on the rest of the page
- adds an "at" to the sentence to improve readability
=> Fix ref tag to close #709

docs/basics/101-139-gin.rst
=> GIN: On using Gin as an autoenabled special remote

.github/workflows/github-action.yml, docs/basics/101-110-run2.rst, docs/basics/101-113-summary.rst
This adds a short paragraph in the chapter on datalad run's input and output options,
and adds a bullet point in the summary of datalad run, on the recently introduced
--assume-ready flag that skips the preparation of --inputs and --outputs if a user
has retrieved/unlocked them already
Fixes #697.
ping @mih
=> Mention --assume-ready of datalad-run

docs/_templates/sidebarintro.html
Found some absolute links that made it hard to find the FAQ in the rendering of #717. Feel free to close without discussion if there's a good reason to use absolute links.
=> ENH: Relative links in sidebar

docs/basics/101-180-FAQ.rst
https://zenodo.org/record/3512712 resolves to 0.12.0rc6. Using record ID noted at the bottom here:
I assumed that you explicitly preferred the Zenodo URL over DOI, so updated the record number without switching to DOI. I'm not sure about dropping the explicit link syntax... RST should render this as a link, but possibly there's a good reason for keeping it as an explicit RST link?
=> ENH: Use Zenodo record that resolves to latest version

docs/basics/101-141-push.rst
Fix parts that #482 did not address for #481.
=> Fix inconsistent description of push behavior

docs/basics/101-108-run.rst, docs/basics/101-117-sharelocal2.rst, docs/basics/101-123-config2.rst, docs/basics/101-130-yodaproject.rst, docs/basics/101-138-sharethirdparty.rst, docs/beyond_basics/101-170-dataladrun.rst, docs/code_from_chapters/OHBM.rst, docs/code_from_chapters/yale.rst, docs/intro/user_types.rst, docs/intro/windows.rst, docs/usecases/HCP_dataset.rst, docs/usecases/datasets.rst, docs/usecases/provenance_tracking.rst, docs/usecases/reproducible-paper.rst, docs/usecases/reproducible_neuroimaging_analysis_simple.rst
also contains one link fix for `https://github.com/datalad-handbook/couse` (couse -> course)
=> Fix typos using codespell

docs/basics/101-137-history.rst
* git reset: Removes commits _since_ not _until_ COMMIT
* commit range wording
=> Fix errors in 9.3 back and forth in time

docs/basics/101-115-symlinks.rst
Looks like this was also addressed in https://github.com/datalad-handbook/book/pull/595, but seems like that one never got merged into master (but instead went to the inm7 branch).
=> This is the name of the file that was created earlier on.

docs/basics/101-139-gin.rst
Fixes these minor issues found in the handbook.
=> FIX: GIN siblings - fix typo in code and note that ``--url`` should not end with ``.git``

docs/basics/101-140-summary.rst
The monthly linkchecker found that this link 404'ed. Closer inspection revealed that the feature was deprecated.
=> MNT: Fix link to git-annex docs on GitLab, mention deprecation

dataladhandbook_support/directives.py, docs/conf.py
Now also using prefixes per box-type. Here is how it looks
=> Numbered boxes and references

docs/basics/101-130-yodaproject.rst, docs/basics/101-138-sharethirdparty.rst, docs/basics/101-139-dropbox.rst, docs/basics/101-139-figshare.rst, docs/basics/101-139-gin.rst, docs/basics/101-139-gitlfs.rst, docs/basics/101-139-hostingservices.rst, docs/basics/101-139-privacy.rst, docs/basics/101-139-s3.rst, docs/basics/101-141-push.rst, docs/basics/basics-thirdparty.rst, docs/glossary.rst
[Duplicate of #761 in hopes to trigger a readthedocs preview that was somehow lost on the way]
This work-in-progress PR starts a larger effort on restructuring and extending the handbooks content on publishing datasets to third party services.
In particular, it
- separated service-specific walk-throughs into standalone sections. This affected the "intro" section in particular, from which content on configuring dropbox as a special remote, exporting dataset contents to figshare, and using Git-lfs have each been transformed into standalone sections in the chapter. At the moment, there are walk-throughts for dropbox, s3, figshare, git lfs and gin. This new structure may also make it easier to add new services as walk-throughs.
- improved the introduction into the topic of dataset …
=> Refactor the chapter on publishing

docs/basics/101-110-run2.rst
A quick PR to at least somewhere in the handbook make a note about the current, potentially confusing behavior in ``run``s globbing. Thanks to @AKSoo for raising it. Its probably still quite hidden and easy to miss, but I guess better than nowhere.
=> Add a note on how to currently glob for several levels of directories

docs/beyond_basics/101-160-gobig.rst
This reverts commit e7d99b9e4e4518ed834da0ba5c8af1180bda11ed because the link function has been restored.
=> Revert "Links: Remove link to old benchmarks on previous website"

docs/beyond_basics/101-146-providers.rst
Fixes #806
This change adds information on the credential integration with Git
that will become a reality with DataLad 0.16. It walks through a
concrete example to let DataLad use Git credential helper, and points
to the to-be-published technical documentation of this new feature
It would be nice to get your review on this, @bpoldrack.
=> New content: Mention credential integration with Git

docs/basics/101-115-symlinks.rst, docs/basics/101-122-config.rst, docs/basics/101-136-filesystem.rst, docs/usecases/reproducible_neuroimaging_analysis.rst
This PR fixes various typos that were tracked in https://github.com/datalad-handbook/book/issues/733. Closes https://github.com/datalad-handbook/book/issues/733.
=> [ENH] Fix various typos

docs/intro/installation.rst
This arose from #833, which revealed an urgent need to document the difficulties of installing DataLad on M1 macs due to the inavailability of git-annex from brew. Thanks to  @anadiasmaile's patience, we walked through the installation instructions for a standalone git-annex install created by Fede and Vera in the Office hour, and a new paragraph on M1 macs links to those instructions now.
=> Installation: Detail the current workarounds for installations on M1 Macs

docs/basics/101-139-s3.rst
add `=`
remove `<>` (may confuse non-technical users)
=> minor fixes to 'Amazon S3 as a special remote'

docs/basics/101-105-install.rst, docs/basics/101-108-run.rst, docs/basics/101-116-sharelocal.rst, docs/basics/101-135-help.rst, docs/basics/101-146-gists.rst, docs/beyond_basics/101-147-riastores.rst, docs/beyond_basics/101-163-summary.rst, docs/code_from_chapters/ABCD.rst, docs/intro/executive_summary.rst, docs/intro/user_types.rst, docs/teaching.rst, docs/usecases/intro.rst
Its unclear why they suddendly stopped working, but now those sections
are linked via their ref, which should be more resilient anyway.
Thanks monthly linkcheck!
=> Link fixes: Remove or replace a range of relative links

docs/intro/installation.rst
Adding a link to an additional step-by-step instruction guide to install git-annex on M1 Mac using Homebrew and Rosetta 2 via command line
=> git-annex installation instructions for M1 Mac

docs/beyond_basics/101-179-gitignore.rst
those annoyed me seeing them enough to bring up. Also a user reported a simple `datalad containers-run` snippet  failing because repo was "dirty" because of some `._DS_stores` emerging from previous steps but not being committed, as they shouldn't.
I even started wondering if we should "by default" (procedure?) define `.gitignore` in new datasets to make the world a better place? ;)
=> ENH: git a code snippet to define a typical collection of git ignores

docs/intro/installation.rst
=> update windows installation instructions

docs/intro/installation.rst
Fixes the recommended method for datalad-installer (`/git-annex` part was missing).
This is a follow-up to PR #868 and issue #865.
=> Update git-annex install method for Windows

docs/r.rst
This issue was brought to light by  https://github.com/datalad/datalad/pull/7223: A URL such as ``handbook.datalad.org/r.html?install`` got redirected to ``handbook.datalad.org/en/latest/r.html?install=`` - while the language and version redirection was fine, this automatic redirection seemed to have appended a trailing equal sign to the query string.
This broke the logic in the JS-based redirection function, which would match the query string in the URL to the defined redirection targets IDs in r.html (i.e., ``install=`` wouldn't match the defined ``install`` anymore). While the cause for that appended equal sign is not quite clear to me, my suspicion is that its a (temporary) problem on readthedocs side, which performs the automatic redirection to default language and versions. This …
=> JS: Work around a redirection glitch that appends equal signs to query strings

docs/basics/101-101-create.rst, docs/conf.py
This leads to all dataset IDs being identical.
This PR is not exhaustively annotating everything.
=> Avoid a global random seed fix

.appveyor.yml, requirements-devel.txt
In less than 1k log lines, this makes a (full) rebuild of the handbook, including execution of runrecords.
It uses the standard build setup documented for the handbook.
Any resulting diff to the `doc/` directory (i.e. updated runrecords) is visualized at the end of the log, and is made available for download at a URL that is also shown at the very end.
With this diff contributors/maintainers can decide to incorporate the changes, in full or partially into their PRs.
=> Complete workflow to rebuild runrecords

docs/basics/101-135-help.rst, docs/basics/_examples/DL-101-135-102
Those have a random suffix and blow up the diff unneccessarily
=> Strip PATH listing from `wtf` when it has tmp dirs

docs/contributing.rst
Adds info about the CI build option to the contributing page. Fixes #886
=> Add info on automatic CI builds to Contributing

docs/_templates/layout.html
Fixes #884.
The ``{{ title }}`` placeholder in ``layout.html`` exposes the 'section-number' individually in span element due to a feature request in Sphinx since Sphinx version 2.3.1 (sphinx-doc/sphinx#6613). This breaks a meta tag that includes the page title, spilling the title as a random string into the body of each page, and also spilling unrelated other HTML meta tags from the head into the body.
In practice, this leads to a rendering bug in the HTML version, and also, as this meta tag was originally used for social card support, in the social cards of any handbook links.
As the underlying problem won't be fixed on Sphinx side, this change removes the problematic meta tag entirely. I'm also decreasing the manual meta tag index that assembles the description in the social card from …
=> Remove broken meta data tag that garbled html and social card rendering

docs/basics/101-139-gin.rst
I wished we called our repositories `repoy`: it sounds cuter. ;-p
=> fix typo in GIN page

.appveyor.yml, docs/beyond_basics/101-168-dvc.rst, docs/beyond_basics/_examples/DL-101-168-121, docs/beyond_basics/_examples/DL-101-168-122, docs/beyond_basics/_examples/DL-101-168-124, docs/beyond_basics/_examples/DL-101-168-131, docs/beyond_basics/_examples/DL-101-168-141, docs/beyond_basics/_examples/DL-101-168-159, docs/beyond_basics/_examples/DL-101-168-160, docs/beyond_basics/_examples/DL-101-168-161, docs/beyond_basics/_examples/DL-101-168-165, docs/beyond_basics/_examples/DL-101-168-166, docs/beyond_basics/_examples/DL-101-168-173, docs/beyond_basics/_examples/DL-101-168-177, docs/beyond_basics/_examples/DL-101-168-178, docs/beyond_basics/_examples/DL-101-168-179, docs/beyond_basics/_examples/DL-101-168-190
Minor fixes for things I noticed when preparing for a workshop. See commit messages for details.
Lacks run records, which prevents merge, but depends on appveyor succeeding (see below), so I leave this in draft mode. Otherwise quite complete.
Remaining todos and issues (help welcome):
=> Update the DVC section

docs/contributing.rst
The project uses requirements and requirements-devel, the latter of which contains datalad-container and Python packages used in the examples. This commit includes both in installation instructions.
Another one-line change adds consistency in putting make in verbatim.
Side note: I had to play around a bit to make the build happen on my Fedora PC and found out that the best solution is to remove only the run records that my changes touched (and not use the entire clean-build or clean-beyond-basics), otherwise the run would take long and eventually fail due to some installation-specific issues (e.g. credentials, IIRC hcp, in beyond-basics; or containers in basics). In the end, I felt that using the appveyor build may be the best way forward for me. But all this wasn't hard to figure out …
=> Include requirements-devel in contributing guide

.readthedocs.yml
This change adds the "build" configuration option for ReadTheDocs, and requires Ubuntu 22.04 LTS.
Python verison is also included in the "build" section, as old way of declaration is deprecated. We use this opportunity to bump Python to v3.9 (matching current debian stable) as 3.7 nears its EOL.
The change is prompted by build failure, after requirements pulled in urllib3 v2.0.x, which removed support for OpenSSL versions earlier than 1.1.1. Build error indicated openssl 1.0.2n which would imply we might even have been on 18.04 (?). Fixes #954
=> Declare / update RTD build environment (Ubuntu 22.04)

docs/intro/installation.rst
delete option that do not exist anymore
add option about openssh, as of  https://github.com/datalad/datalad/issues/5829#issuecomment-1068773537
=> Update installation.rst for GIt for windows install

docs/intro/installation.rst
Removing cmdline prompt character (>) from the git-annex section so it can be copy-pasted into cmdline and without making any edits. As it is currently, user would have to manually delete the > character before the command runs. Super minor change but thought it might be useful for others
=> Removing cmdline prompt character installation.rst

docs/basics/101-122-config.rst, docs/beyond_basics/101-160-gobig.rst, docs/beyond_basics/101-182-catalog.rst
The new links point to the new location of the referenced resources.
=> Update broken links

.github/workflows/linkcheck.yml
Was failing due to outdated package lists.
Also try to speed up installation with `eatmydata`
=> Robustify linkchecker workflow

docs/basics/101-121-siblings.rst, docs/basics/_examples/DL-101-121-101, docs/beyond_basics/101-182-catalog.rst, docs/beyond_basics/_examples/DL-101-182-113
Github allows download using the first 8 significant chars of a sha1 alone.
Closes #1000
=> Shorten blob URLs

.github/workflows/codespell.yml, docs/basics/101-106-nesting.rst, docs/basics/101-107-summary.rst, docs/basics/101-127-yoda.rst, docs/basics/101-132-advancednesting.rst, docs/usecases/supervision.rst, pyproject.toml
so we could just run `codespell` and not rely on config being only github action specific
=> codespell: move configuration into pyproject.toml and fix "re-use" typo

docs/basics/101-132-advancednesting.rst, docs/basics/_examples/DL-101-132-108a
This makes the find-out-more fit two full pages and adds information that previously was found to be lacking.
=> Extend FOM on datalad status with json_pp format demo

docs/book_appendix.rst, docs/index.rst, docs/licenses.rst
All other information is only available in the sources. Including them in the book itself has the advantage that appropriate term declarations are also available in each (offline) PDF.
The content in the PR may not be complete. I only went through the content that is included in the print version, and focused on graphics. However, the text is phrased in a way that should not imply a comprehensive assessment.
=> Add a dedicated section on copyright and licenses

docs/basics/101-141-push.rst
I think the heading works just as fine without the prefix. Shorter is better.
=> Stop excessive colonization

docs/intro/windows.rst
The description is changed to state the correct sizes in characters (because those are immediately relevant, not the bitsize, even if directly convertable).
Thanks to @NemoAndrea for reporting!
Closes #977
=> Correct the description of hash-size impact on Windows paths

docs/basics/basics-annex.rst, docs/basics/basics-collaboration.rst, docs/basics/basics-configuration.rst, docs/basics/basics-containers.rst, docs/basics/basics-datasets.rst, docs/basics/basics-help.rst, docs/basics/basics-run.rst, docs/basics/basics-thirdparty.rst, docs/basics/basics-yoda.rst, docs/beyond_basics/basics-advancedoptions.rst, docs/beyond_basics/basics-dataladinternals.rst, docs/beyond_basics/basics-extensions.rst, docs/beyond_basics/basics-hpc.rst, docs/beyond_basics/basics-retrospective.rst, docs/beyond_basics/basics-scaling.rst, docs/beyond_basics/basics-specialpurpose.rst
This conflates the purpose of an index and a TOC. We have both and should not cross-populate information to keep things lean and clean.
=> Remove index entries for chapters

docs/index.rst, docs/perma/README, docs/perma/book-intro-v1.rst, docs/r.rst
The first use case is a page for the printed introduction book. This page would provide or link to any updates we may need to make in the future, after the book is printed.
=> Minimal setup for "perma-content"

docs/conf.py, requirements.txt
More recent versions of Sphinx stopped shipping jquery, which is required for toggling boxes and the page progress bar. Instead, we're now using a dedicated sphinx extension sphinxcontrib.jquery
fixes #1071
=> Fix toggling by using jquery

docs/basics/101-139-s3.rst, docs/intro/howto.rst
This replaces one instance of the jargon "subject" in the Basics of the handbook in response to #1055. There are more instances in specialized neuro usecases or advanced parts such as the section on the HCP dataset
=> replace 'subject' with 'brain'

docs/usecases/_examples/ml-102, docs/usecases/ml-analysis.rst
This PR
- Removes the Windows-workaround for text2git - this procedure has been long functional on Windows
- Removes a version note for a workaround that affected datalad versions 0.12 to 0.13.4
It also removes a newly created index entry - I hope this does not conflict with your work, @mih
=> Modernizations to ML usecase

docs/code_from_chapters/ABCD.rst, docs/code_from_chapters/DLBasicsMPI.rst, docs/code_from_chapters/usecase_ml_code.rst, docs/intro/narrative.rst, docs/intro/windows.rst
It is only kept in three instances:
- As an installation header (because at the moment its Windows 10 and 11 where datalad can be installed, not prior versions)
- In references to minimal Windows versions that introduced a certain feature (e.g., long paths)
- in the information about the windows version with which we tested the handbook under windows
=> Remove unecessary Windows version specification where possible

docs/basics/101-103-modify.rst, docs/usecases/ml-analysis.rst
I find that it is less ambiguous when used as a single word - otherwise, people unfamiliar with the concept might misinterpret the term as broken sentence structure or grammar
Fixes #1093
=> standardize here document to heredoc

docs/basics/101-101-create.rst, docs/basics/101-102-populate.rst, docs/basics/101-103-modify.rst, docs/basics/101-109-rerun.rst, docs/basics/101-110-run2.rst, docs/basics/101-121-siblings.rst, docs/basics/101-130-yodaproject.rst, docs/basics/101-132-advancednesting.rst, docs/basics/101-136-filesystem.rst, docs/usecases/HCP_dataset.rst
in response to https://github.com/datalad-handbook/book/issues/1092
=> Consistently use single quotes as command markup in box titles

docs/basics/101-133-containersrun.rst, docs/basics/101-134-summary.rst, docs/glossary.rst
Replaces the capitalization markup for `Image`.
Closes #1103
=> Use proper terms for container concept

docs/basics/101-136-filesystem.rst, docs/basics/_examples/DL-101-136-182
In response to #1079. This affects the most prominently presented instances of ``datalad remove``, and also removes the remaining mention of the deprecated ``datalad uninstall`` command. Where possible, ``datalad drop`` commands are recommended. One example output diff is needed from appveyor in this PR.
=> remove mention of 'dl uninstall', favour drop over remove

docs/basics/101-115-symlinks.rst, docs/basics/101-116-sharelocal.rst, docs/basics/101-139-gitlfs.rst, docs/basics/topic/adjustedmode-nosymlinks.rst
Replaces parenthetical constructs with simpler sentences. Also removed double '))' occurrences.
=> Simplify section cross-refs

docs/basics/101-101-create.rst, docs/basics/101-103-modify.rst, docs/basics/101-105-install.rst, docs/basics/101-106-nesting.rst, docs/basics/101-108-run.rst, docs/basics/101-115-symlinks.rst, docs/basics/101-116-sharelocal.rst, docs/basics/101-119-sharelocal4.rst, docs/basics/101-124-procedures.rst, docs/basics/101-130-yodaproject.rst, docs/basics/101-135-help.rst, docs/basics/101-136-cheatsheet.rst, docs/basics/101-139-figshare.rst, docs/basics/101-139-hostingservices.rst, docs/basics/101-139-s3.rst
=> In Basics, remove 'below' when refering to things that can float away

docs/basics/101-127-yoda.rst
It is only important that outputs are not placed into the `inputs/` directory.
Using an `output/` directory is OK, though. However, it can become awkward, if such a data module is used as input to another. File paths, seen from the YODA root would then be: `inputs/outputs/something.dat`
This is a non-invasive change that accounts enough for this aspect, IMHO.
=> Avoid declaring an `output/` directory as mandatory

.zenodo.json, docs/beyond_basics/101-169-cluster.rst
Hey,
as mentioned in #1117, I added a small note in the cluster section of the handbook, that datalad may be installed per Easybuild.
=> add short sentence on datalad via easybuild

docs/beyond_basics/101-170-dataladrun.rst
This PR proposes to change `$JOB-ID` to `$JOBID` in the paragraph of text following a code snippet that includes `$JOBID` to be consistent with the code  and the following sentence in the same paragraph. Even though the text refers to "Job-ID" multiple times, the variable name in the code snippet is `$JOBID`.
=> Fix typo: $JOB-ID ->  $JOBID

docs/beyond_basics/101-147-riastores.rst
=> fix RIA URL spec

docs/beyond_basics/101-182-catalog.rst
The demo site was moved from github pages to netlify
Note, close https://github.com/datalad/datalad-catalog/issues/422 when this is merged.
=> Update datalad-catalog demo site URL

docs/basics/101-106-nesting.rst, docs/basics/101-107-summary.rst, docs/basics/101-110-run2.rst, docs/basics/101-121-siblings.rst, docs/basics/101-134-summary.rst, docs/basics/101-136-filesystem.rst, docs/basics/101-139-hostingservices.rst, docs/basics/101-146-gists.rst, docs/beyond_basics/101-145-hooks.rst, docs/beyond_basics/101-160-gobig.rst, docs/beyond_basics/101-170-dataladrun.rst, docs/beyond_basics/101-171-enki.rst, docs/beyond_basics/101-179-gitignore.rst, docs/beyond_basics/101-181-metalad.rst, docs/code_from_chapters/ABCD.rst, docs/code_from_chapters/DLBasicsMPI.rst, docs/code_from_chapters/dgpa.rst, docs/code_from_chapters/osoh.rst, docs/code_from_chapters/usecase_ml_code.rst, docs/code_from_chapters/yale.rst, docs/usecases/ml-analysis.rst
This fixes the usage of contraction *it's* (it is / it has) and possessive *its*, as far as I could grep.
=> Fix "it's" vs "its" usage

docs/basics/101-136-cheatsheet.rst
Clicking on the image in the handbook leads to a 404. This PR fixes the link.
=> Fix wrong branch name in link to cheatsheet

docs/basics/101-139-s3.rst
This incorporates the corrected commands and information from #1224.
Fixes #1224.
=> Fixes to the S3 walk-through

docs/conf.py
see https://about.readthedocs.com/blog/2024/07/addons-by-default
After a brief exploration, the project builds fine even when the new AddOns are enabled and this configuration hasn't been set - but it also works with this configuration, so why not be an early adopter.
=> Preemptively add rdt configuration recommendation

docs/basics/101-139-s3.rst
Adding public access to an S3 bucket for a publicly available datalad repository via opentofu is quite a few lines of configuration because you essentially have to configure it twice.
I put this into the "Advanced example" category because it is only useful for people using terraform / opentofu.
=> add example terraform config for an s3 bucket

docs/basics/101-110-run2.rst
Hi, I think the word "crop" in this sentence may be slightly misleading and should be replaced with "resize".
To me the image operations of cropping and resizing are very different.
Since the text and examples beyond that sentence all talk about resizing, it should also be called resizing here as well.
=> replace word 'crop' with 'resize'
